// ADSMOD/client/src/components/WizardNavigationFooter.tsx
import React from 'react';

interface WizardNavigationFooterProps {
    isLoading: boolean;
    isFirstPage: boolean;
    isLastPage: boolean;
    onClose: () => void;
    onNext: () => void;
    onPrevious: () => void;
    onConfirm: () => void;
    confirmIdleLabel: string;
    confirmLoadingLabel: string;
}

export const WizardNavigationFooter: React.FC<WizardNavigationFooterProps> = ({
    isLoading,
    isFirstPage,
    isLastPage,
    onClose,
    onNext,
    onPrevious,
    onConfirm,
    confirmIdleLabel,
    confirmLoadingLabel,
}) => (
    <div className="wizard-footer">
        <button className="secondary" onClick={onClose} disabled={isLoading}>
            Cancel
        </button>
        {!isFirstPage && (
            <button className="secondary" onClick={onPrevious} disabled={isLoading}>
                Previous
            </button>
        )}
        {!isLastPage && (
            <button className="primary" onClick={onNext} disabled={isLoading}>
                Next
            </button>
        )}
        {isLastPage && (
            <button className="primary" onClick={onConfirm} disabled={isLoading}>
                {isLoading ? confirmLoadingLabel : confirmIdleLabel}
            </button>
        )}
    </div>
);

// app/ml_client/src/app/features/training/components/wizard-navigation-footer.component.ts
import { Component, input, output } from '@angular/core';

@Component({
    selector: 'adsmod-wizard-navigation-footer',
    standalone: true,
    template: `
        <div class="wizard-footer">
            <button class="secondary" type="button" [disabled]="isLoading()" (click)="closed.emit()">Cancel</button>
            @if (!isFirstPage()) {
                <button class="secondary" type="button" [disabled]="isLoading()" (click)="previous.emit()">Previous</button>
            }
            @if (!isLastPage()) {
                <button class="primary" type="button" [disabled]="isLoading()" (click)="next.emit()">Next</button>
            }
            @if (isLastPage()) {
                <button class="primary" type="button" [disabled]="isLoading()" (click)="confirmed.emit()">
                    {{ isLoading() ? confirmLoadingLabel() : confirmIdleLabel() }}
                </button>
            }
        </div>
    `,
})
export class WizardNavigationFooterComponent {
    readonly isLoading = input(false);
    readonly isFirstPage = input(false);
    readonly isLastPage = input(false);
    readonly confirmIdleLabel = input.required<string>();
    readonly confirmLoadingLabel = input.required<string>();
    readonly closed = output<void>();
    readonly next = output<void>();
    readonly previous = output<void>();
    readonly confirmed = output<void>();
}
