// ADSMOD/client/src/pages/ModelsPage.tsx
import React, { useState, useCallback, useMemo } from 'react';
import { ModelCard } from '../components/ModelCard';
import { NumberInput } from '../components/UIComponents';
import { ADSORPTION_MODELS } from '../adsorptionModels';
import type { ModelParameters, FittingPayload } from '../types';

type OptimizationMethod = FittingPayload['optimization_method'];

interface OptimizationMethodOption {
    value: OptimizationMethod;
    label: string;
}

const OPTIMIZATION_METHOD_OPTIONS: readonly OptimizationMethodOption[] = [
    { value: 'LSS', label: 'Least Squares (LSS)' },
    { value: 'BFGS', label: 'BFGS' },
    { value: 'L-BFGS-B', label: 'L-BFGS-B' },
    { value: 'Nelder-Mead', label: 'Nelder-Mead' },
    { value: 'Powell', label: 'Powell' },
];

const parseOptimizationMethod = (value: string): OptimizationMethod | null => {
    const option = OPTIMIZATION_METHOD_OPTIONS.find((candidate) => candidate.value === value);
    return option?.value ?? null;
};

interface ModelState {
    enabled: boolean;
    config: ModelParameters;
}

interface ModelsPageProps {
    modelStates: Record<string, ModelState>;
    onParametersChange: (modelName: string, parameters: ModelParameters) => void;
    onToggle: (modelName: string, enabled: boolean) => void;
    maxIterations: number;
    onMaxIterationsChange: (value: number) => void;
    optimizationMethod: OptimizationMethod;
    onOptimizationMethodChange: (value: OptimizationMethod) => void;
    fittingStatus: string;
    onStartFitting: () => void;
    onResetFittingStatus: () => void;
    availableDatasets: string[];
    selectedDataset: string | null;
    onDatasetSelect: (name: string | null) => void;
    nistOptionValue: string;
}

export const ModelsPage: React.FC<ModelsPageProps> = ({
    modelStates,
    onParametersChange,
    onToggle,
    maxIterations,
    onMaxIterationsChange,
    optimizationMethod,
    onOptimizationMethodChange,
    fittingStatus,
    onStartFitting,
    onResetFittingStatus,
    availableDatasets,
    selectedDataset,
    onDatasetSelect,
    nistOptionValue,
}) => {
    const [expandedId, setExpandedId] = useState<string | null>(null);

    const handleCardToggle = useCallback((modelId: string) => {
        setExpandedId((prev) => (prev === modelId ? null : modelId));
    }, []);

    const handleEnabledChange = useCallback(
        (modelName: string, enabled: boolean) => {
            onToggle(modelName, enabled);
        },
        [onToggle]
    );

    const handleConfigChange = useCallback(
        (modelName: string, config: ModelParameters) => {
            onParametersChange(modelName, config);
        },
        [onParametersChange]
    );

    const handleOptimizationMethodChange = useCallback(
        (event: React.ChangeEvent<HTMLSelectElement>) => {
            const nextMethod = parseOptimizationMethod(event.target.value);
            if (nextMethod) {
                onOptimizationMethodChange(nextMethod);
            }
        },
        [onOptimizationMethodChange]
    );

    const gridCells = useMemo(() => {
        return ADSORPTION_MODELS.map((model) => {
            const state = modelStates[model.name] || {
                enabled: true,
                config: {},
            };

            return (
                <ModelCard
                    key={model.id}
                    model={model}
                    isExpanded={expandedId === model.id}
                    isEnabled={state.enabled}
                    currentConfig={state.config}
                    onToggle={handleCardToggle}
                    onEnabledChange={handleEnabledChange}
                    onConfigChange={handleConfigChange}
                />
            );
        });
    }, [expandedId, modelStates, handleCardToggle, handleEnabledChange, handleConfigChange]);

    return (
        <div className="models-page">
            <div className="fitting-config-panel">
                <div className="models-header-row">
                    <div className="models-title-block">
                        <h3>Fitting Configuration</h3>
                        <p>Configure the optimizer and run the fit.</p>
                    </div>
                </div>

                <div className="fitting-main-layout">
                    <div className="fitting-controls-column">
                        <div className="fitting-controls-row">
                            <div className="control-group">
                                <label className="field-label">Dataset</label>
                                <div className="fitting-dataset-row">
                                    <select
                                        value={selectedDataset || ''}
                                        onChange={(e) => onDatasetSelect(e.target.value || null)}
                                        className="select-input fitting-dataset-select"
                                    >
                                        <option value="">
                                            {availableDatasets.length === 0 ? 'No datasets available' : 'Select a dataset'}
                                        </option>
                                        <option value={nistOptionValue}>NIST-A Collection</option>
                                        {availableDatasets.map((name) => (
                                            <option key={name} value={name}>
                                                {name}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                            </div>
                            <div className="control-group">
                                <NumberInput
                                    label="Max iterations"
                                    value={maxIterations}
                                    onChange={onMaxIterationsChange}
                                    min={1}
                                    max={1000000}
                                    step={1}
                                    precision={0}
                                />
                            </div>
                            <div className="control-group">
                                <label className="field-label">Optimization method</label>
                                <select
                                    value={optimizationMethod}
                                    onChange={handleOptimizationMethodChange}
                                    className="select-input"
                                >
                                    {OPTIMIZATION_METHOD_OPTIONS.map((option) => (
                                        <option key={option.value} value={option.value}>
                                            {option.label}
                                        </option>
                                    ))}
                                </select>
                            </div>
                            <div className="control-group">
                                <div className="fitting-action-buttons">
                                    <button className="primary fitting-action-primary" onClick={onStartFitting} type="button">
                                        Start Fitting
                                    </button>
                                    <button className="secondary fitting-action-secondary" onClick={onResetFittingStatus} type="button">
                                        Reset Log
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="fitting-status-column">
                        <div className="fitting-status-box">
                            <div className="status-label">Fitting Log:</div>
                            <pre className="status-text">{fittingStatus || 'Ready to start...'}</pre>
                        </div>
                    </div>
                </div>
            </div>

            <hr className="section-separator" />

            <div className="models-grid-header">
                <h3>Select Adsorption Models</h3>
            </div>

            <div className="models-grid">{gridCells}</div>
        </div>
    );
};

export default ModelsPage;

// app/client/src/app/features/fitting/models-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { ADSORPTION_MODELS } from '../../core/constants/adsorption-models';
import { CoreWorkspaceStore, OptimizationMethod } from '../../core/state/core-workspace.store';
import { HeaderTabsComponent } from '../../layout/header-tabs.component';
import type { ModelParameters } from '../../models/fitting.model';
import { NumberInputComponent } from '../../shared/components/number-input/number-input.component';
import { ModelCardComponent } from './model-card.component';

interface OptimizationMethodOption {
    value: OptimizationMethod;
    label: string;
}

const OPTIMIZATION_METHOD_OPTIONS: readonly OptimizationMethodOption[] = [
    { value: 'LSS', label: 'Least Squares (LSS)' },
    { value: 'BFGS', label: 'BFGS' },
    { value: 'L-BFGS-B', label: 'L-BFGS-B' },
    { value: 'Nelder-Mead', label: 'Nelder-Mead' },
    { value: 'Powell', label: 'Powell' },
];

const parseOptimizationMethod = (value: string): OptimizationMethod | null => {
    const option = OPTIMIZATION_METHOD_OPTIONS.find((candidate) => candidate.value === value);
    return option?.value ?? null;
};

@Component({
    selector: 'adsmod-models-page',
    standalone: true,
    imports: [ModelCardComponent, NumberInputComponent, HeaderTabsComponent],
    template: `
        <div class="route-workspace route-workspace-fitting">
            <aside class="route-rail route-rail-fitting" aria-label="Fitting overview">
                <div class="route-rail-brand">
                    <div class="route-rail-logo" aria-hidden="true">AD</div>
                    <div class="route-rail-wordmark">ADSMOD</div>
                </div>
                <div class="route-rail-copy">
                    <h1>Fitting</h1>
                    <p>Configure the optimizer and run the fit.</p>
                </div>
            </aside>

            <section class="route-canvas route-canvas-fitting">
                <div class="route-tabs-row">
                    <adsmod-header-tabs />
                </div>

                <div class="models-page">
                    <div class="fitting-config-panel">
                        <div class="models-header-row">
                            <div class="models-title-block">
                                <h3>Fitting Configuration</h3>
                            </div>
                        </div>

                        <div class="fitting-main-layout">
                            <div class="fitting-controls-column">
                                <div class="fitting-controls-row">
                                    <div class="control-group">
                                        <label class="field-label">Dataset</label>
                                        <div class="fitting-dataset-row">
                                            <select
                                                [value]="store.selectedDataset() || ''"
                                                (change)="selectDataset($event)"
                                                class="select-input fitting-dataset-select"
                                            >
                                                <option value="">{{ store.availableDatasets().length === 0 ? 'No datasets available' : 'Select a dataset' }}</option>
                                                <option [value]="store.nistDatasetOption">NIST-A Collection</option>
                                                @for (datasetName of store.availableDatasets(); track datasetName) {
                                                    <option [value]="datasetName">{{ datasetName }}</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <adsmod-number-input
                                            label="Max iterations"
                                            [value]="store.maxIterations()"
                                            [min]="1"
                                            [max]="1000000"
                                            [step]="1"
                                            [precision]="0"
                                            (valueChange)="store.setMaxIterations($event)"
                                        />
                                    </div>
                                    <div class="control-group">
                                        <label class="field-label">Optimization method</label>
                                        <select
                                            [value]="store.optimizationMethod()"
                                            (change)="selectOptimizer($event)"
                                            class="select-input"
                                        >
                                            @for (option of optimizationOptions; track option.value) {
                                                <option [value]="option.value">{{ option.label }}</option>
                                            }
                                        </select>
                                    </div>
                                    <div class="control-group">
                                        <div class="fitting-action-buttons">
                                            <button class="primary fitting-action-primary" type="button" (click)="startFitting()">
                                                Start Fitting
                                            </button>
                                            <button class="secondary fitting-action-secondary" type="button" (click)="store.resetFittingStatus()">
                                                Reset Log
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="fitting-status-column">
                                <div class="fitting-status-box">
                                    <div class="status-label">Fitting Log:</div>
                                    <pre class="status-text">{{ store.fittingStatus() || 'Ready to start...' }}</pre>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr class="section-separator" />

                    <div class="models-grid-header">
                        <h3>Select Adsorption Models</h3>
                    </div>

                    <div class="models-grid">
                        @for (model of models; track model.id) {
                            <adsmod-model-card
                                [model]="model"
                                [isExpanded]="expandedModel() === model.id"
                                [isEnabled]="store.modelStates()[model.name].enabled"
                                [currentConfig]="store.modelStates()[model.name].config"
                                (toggle)="toggleExpanded($event)"
                                (enabledChange)="store.setModelEnabled(model.name, $event)"
                                (configChange)="updateModelConfig(model.name, $event)"
                            />
                        }
                    </div>
                </div>
            </section>
        </div>
    `,
})
export class ModelsPageComponent {
    protected readonly store = inject(CoreWorkspaceStore);
    protected readonly models = ADSORPTION_MODELS;
    protected readonly optimizationOptions = OPTIMIZATION_METHOD_OPTIONS;
    protected readonly expandedModel = signal<string | null>(null);

    protected toggleExpanded(modelId: string): void {
        this.expandedModel.set(this.expandedModel() === modelId ? null : modelId);
    }

    protected selectDataset(event: Event): void {
        const select = event.target as HTMLSelectElement;
        this.store.setSelectedDataset(select.value);
    }

    protected selectOptimizer(event: Event): void {
        const select = event.target as HTMLSelectElement;
        const method = parseOptimizationMethod(select.value);
        if (method) {
            this.store.setOptimizationMethod(method);
        }
    }

    protected updateModelConfig(modelName: string, config: ModelParameters): void {
        this.store.setModelParameters(modelName, config);
    }

    protected async startFitting(): Promise<void> {
        await this.store.startFitting();
    }
}
