// ADSMOD/client/src/pages/MachineLearningPage.tsx
import React, { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { DatasetBuilderCard } from '../components/DatasetBuilderCard';
import { NewTrainingWizard } from '../components/NewTrainingWizard';
import { ResumeTrainingWizard } from '../components/ResumeTrainingWizard';
import { TrainingSetupRow } from '../components/TrainingSetupRow';
import { InfoModal } from '../components/InfoModal';
import { TrainingHistoryChartPanel } from '../features/training/components/TrainingHistoryChartPanel';
import { useTrainingActionRunner } from '../features/training/hooks/useTrainingActionRunner';
import type {
    CheckpointFullDetails,
    TrainingConfig,
    CheckpointInfo,
    TrainingStatus,
    ResumeTrainingConfig,
    TrainingHistoryPoint,
    TrainingMetrics,
    ProcessedDatasetInfo,
    DatasetFullInfo,
    InfoModalData,
} from '../types';
import {
    fetchCheckpoints,
    startTraining,
    resumeTraining,
    stopTraining,
    getTrainingStatus,
    fetchProcessedDatasets,
    deleteDataset,
    getTrainingDatasetInfo,
    deleteCheckpoint,
    fetchCheckpointDetails,
} from '../services';

const ARCHIVED_DATASET_PREFIX = 'archived::';

// Default training configuration
const DEFAULT_CONFIG: TrainingConfig = {
    batch_size: 16,
    shuffle_dataset: true,
    max_buffer_size: 256,
    selected_model: 'SCADS Series',
    dropout_rate: 0.1,
    num_attention_heads: 2,
    num_encoders: 2,
    molecular_embedding_size: 64,
    epochs: 2,
    dataloader_workers: 0,
    prefetch_factor: 1,
    pin_memory: true,
    use_device_GPU: true,
    device_ID: 0,
    use_mixed_precision: false,
    use_jit: false,
    jit_backend: 'inductor',
    use_lr_scheduler: false,
    initial_lr: 1e-4,
    target_lr: 1e-5,
    constant_steps: 5,
    decay_steps: 10,
    save_checkpoints: false,
    checkpoints_frequency: 5,
    custom_name: '',
};

interface MetricCardProps {
    label: string;
    value: string;
    icon?: string;
    color?: string;
}

const MetricCard: React.FC<MetricCardProps> = ({ label, value, icon, color = 'var(--primary-600)' }) => (
    <div className="metric-card">
        <div className="metric-label">{icon && <span className="metric-icon">{icon}</span>}{label}</div>
        <div className="metric-value" style={{ color }}>{value}</div>
    </div>
);

const CHART_COLORS = {
    loss: '#f59e0b',
    valLoss: '#2563eb',
    metric: '#16a34a',
    valMetric: '#9333ea',
};

const formatLossValue = (value: number | undefined): string => {
    const safeValue = typeof value === 'number' ? value : 0;
    return safeValue.toFixed(4);
};

const formatMetricValue = (value: number | undefined, asPercent: boolean): string => {
    const safeValue = typeof value === 'number' ? value : 0;
    if (asPercent) {
        return `${(safeValue * 100).toFixed(2)}%`;
    }
    return safeValue.toFixed(4);
};

const buildDatasetMetadataModalData = (info: DatasetFullInfo): InfoModalData => ({
    'Dataset Label': info.dataset_label,
    'Created At': info.created_at,
    'Total Samples': info.total_samples,
    'Train Samples': info.train_samples,
    'Validation Samples': info.validation_samples,
    'Sample Fraction': info.sample_size,
    'Validation Fraction': info.validation_size,
    'Min Measurements': info.min_measurements,
    'Max Measurements': info.max_measurements,
    'SMILES Length': info.smile_sequence_size,
    'Max Pressure': info.max_pressure,
    'Max Uptake': info.max_uptake,
    'SMILES Vocabulary': info.smile_vocabulary_size,
    'Adsorbents Count': info.adsorbent_vocabulary_size,
    'Normalization': info.normalization_stats,
});

const buildCheckpointDetailsModalData = (details: CheckpointFullDetails): InfoModalData => ({
    Name: details.name,
    'Epochs Trained': details.epochs_trained,
    'Final Loss': details.final_loss?.toFixed(6) ?? 'N/A',
    'Is Compatible': details.is_compatible ? 'Yes' : 'No',
    'Created At': details.created_at || 'Unknown',
});

type TrainingViewId = 'processing' | 'datasets' | 'checkpoints' | 'dashboard';

interface TrainingViewSpec {
    id: TrainingViewId;
    label: string;
    description: string;
    icon: React.ReactNode;
}

const TRAINING_VIEWS: readonly TrainingViewSpec[] = [
    {
        id: 'processing',
        label: 'Data Processing',
        description: 'Prepare adsorption datasets for model training.',
        icon: (
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
        ),
    },
    {
        id: 'datasets',
        label: 'Train datasets',
        description: 'Choose a processed dataset and configure a new training run.',
        icon: (
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <rect x="3" y="4" width="18" height="6" rx="1" />
                <rect x="3" y="14" width="18" height="6" rx="1" />
                <line x1="7" y1="7" x2="7.01" y2="7" />
                <line x1="7" y1="17" x2="7.01" y2="17" />
            </svg>
        ),
    },
    {
        id: 'checkpoints',
        label: 'Checkpoints',
        description: 'Review saved checkpoints and resume a training run.',
        icon: (
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <rect x="4" y="4" width="16" height="16" rx="2" />
                <path d="M8 9h8" />
                <path d="M8 13h8" />
                <path d="M8 17h5" />
            </svg>
        ),
    },
    {
        id: 'dashboard',
        label: 'Training Dashboard',
        description: 'Track training progress, metrics, and logs in real time.',
        icon: (
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M3 3v18h18" />
                <path d="M19 9l-5 5-4-4-3 3" />
            </svg>
        ),
    },
];

const sanitizeProcessedDatasets = (datasets: ProcessedDatasetInfo[]): ProcessedDatasetInfo[] => {
    const uniqueByLabel = new Map<string, ProcessedDatasetInfo>();

    datasets.forEach((dataset) => {
        const label = String(dataset.dataset_label || '').trim();
        if (!label || label.startsWith(ARCHIVED_DATASET_PREFIX)) {
            return;
        }
        if (!uniqueByLabel.has(label)) {
            uniqueByLabel.set(label, dataset);
        }
    });

    return Array.from(uniqueByLabel.values());
};

export const MachineLearningPage: React.FC = () => {
    const [activeView, setActiveView] = useState<TrainingViewId>('processing');

    const [config, setConfig] = useState<TrainingConfig>(DEFAULT_CONFIG);
    const [checkpoints, setCheckpoints] = useState<CheckpointInfo[]>([]);

    const [trainingStatus, setTrainingStatus] = useState<TrainingStatus>({
        is_training: false,
        current_epoch: 0,
        total_epochs: 0,
        progress: 0,
        metrics: {},
        history: [],
        log: [],
    });

    const [isLoading, setIsLoading] = useState(false);
    const [showNewTrainingWizard, setShowNewTrainingWizard] = useState(false);
    const [showResumeTrainingWizard, setShowResumeTrainingWizard] = useState(false);
    const [resumeConfig, setResumeConfig] = useState<ResumeTrainingConfig>({
        checkpoint_name: '',
        additional_epochs: 10,
    });

    const [processedDatasets, setProcessedDatasets] = useState<ProcessedDatasetInfo[]>([]);
    const [selectedDatasetLabel, setSelectedDatasetLabel] = useState<string | null>(null);
    const [selectedDatasetHash, setSelectedDatasetHash] = useState<string | null>(null);

    const [infoModalOpen, setInfoModalOpen] = useState(false);
    const [infoModalTitle, setInfoModalTitle] = useState('');
    const [infoModalData, setInfoModalData] = useState<InfoModalData | null>(null);

    const openErrorModal = useCallback((title: string, message: string) => {
        setInfoModalTitle(title);
        setInfoModalData({ Message: message });
        setInfoModalOpen(true);
    }, []);

    const pollIntervalRef = useRef<number | null>(null);
    const pollIntervalSecondsRef = useRef<number | null>(null);
    const wasTrainingRef = useRef(false);
    const logContainerRef = useRef<HTMLPreElement>(null);

    useEffect(() => {
        loadCheckpoints();
        loadProcessedDatasets();
        checkStatus();
        return () => stopPolling();
    }, []);

    useEffect(() => {
        if (logContainerRef.current) {
            logContainerRef.current.scrollTop = logContainerRef.current.scrollHeight;
        }
    }, [trainingStatus.log]);

    useEffect(() => {
        if (trainingStatus.is_training) {
            if (!pollIntervalRef.current) {
                const intervalSeconds = trainingStatus.poll_interval
                    ?? pollIntervalSecondsRef.current
                    ?? 1.0;
                startPolling(intervalSeconds);
            }
        } else {
            stopPolling();
        }
    }, [trainingStatus.is_training]);

    const normalizePollingInterval = (intervalSeconds: number | null | undefined) => {
        if (typeof intervalSeconds !== 'number' || Number.isNaN(intervalSeconds)) {
            return null;
        }
        return intervalSeconds < 0 ? 0 : intervalSeconds;
    };

    const startPolling = (intervalSeconds: number = 1.0) => {
        const normalizedInterval = normalizePollingInterval(intervalSeconds) ?? 1.0;
        if (pollIntervalRef.current) {
            window.clearInterval(pollIntervalRef.current);
        }
        pollIntervalSecondsRef.current = normalizedInterval;
        pollIntervalRef.current = window.setInterval(checkStatus, normalizedInterval * 1000);
    };

    const stopPolling = () => {
        if (pollIntervalRef.current) {
            window.clearInterval(pollIntervalRef.current);
            pollIntervalRef.current = null;
        }
    };

    const checkStatus = async () => {
        const status = await getTrainingStatus();
        if (status.error) {
            console.error('Failed to poll status:', status.error);
            return;
        }

        const wasTraining = wasTrainingRef.current;
        wasTrainingRef.current = status.is_training;

        setTrainingStatus({
            is_training: status.is_training,
            current_epoch: status.current_epoch,
            total_epochs: status.total_epochs,
            progress: status.progress,
            metrics: status.metrics || {},
            history: status.history || [],
            log: status.log || [],
            poll_interval: status.poll_interval,
        });

        const nextInterval = normalizePollingInterval(status.poll_interval);
        if (nextInterval !== null && pollIntervalSecondsRef.current !== nextInterval) {
            if (status.is_training) {
                startPolling(nextInterval);
            } else {
                pollIntervalSecondsRef.current = nextInterval;
            }
        }

        if (!status.is_training && wasTraining) {
            loadCheckpoints();
        }
    };

    const loadCheckpoints = async () => {
        const result = await fetchCheckpoints();
        if (!result.error) {
            setCheckpoints(result.checkpoints);
        }
    };

    const loadProcessedDatasets = async () => {
        const { datasets, error } = await fetchProcessedDatasets();
        if (!error) {
            setProcessedDatasets(sanitizeProcessedDatasets(datasets));
        }
    };

    const handleDeleteDataset = async (label: string) => {
        if (window.confirm(`Are you sure you want to delete dataset '${label}'?`)) {
            const { success, message } = await deleteDataset(label);
            if (success) {
                loadProcessedDatasets();
            } else {
                openErrorModal('Delete Dataset Failed', message || 'Failed to delete dataset.');
            }
        }
    };

    const handleViewDatasetMetadata = async (label: string) => {
        setIsLoading(true);
        const info = await getTrainingDatasetInfo(label);
        setIsLoading(false);

        if (info && info.available) {
            setInfoModalTitle('Dataset Metadata');
            setInfoModalData(buildDatasetMetadataModalData(info));
            setInfoModalOpen(true);
        } else {
            openErrorModal('Dataset Metadata', `Could not fetch details for dataset '${label}'.`);
        }
    };

    const handleDeleteCheckpoint = async (name: string) => {
        if (window.confirm(`Are you sure you want to delete checkpoint '${name}'?`)) {
            const { success, error } = await deleteCheckpoint(name);
            if (success) {
                loadCheckpoints();
            } else {
                openErrorModal('Delete Checkpoint Failed', error || 'Failed to delete checkpoint.');
            }
        }
    };

    const handleViewCheckpointDetails = async (name: string) => {
        const { details, error } = await fetchCheckpointDetails(name);
        if (error) {
            openErrorModal('Checkpoint Details', error);
        } else if (details) {
            setInfoModalTitle('Checkpoint Details');
            setInfoModalData(buildCheckpointDetailsModalData(details));
            setInfoModalOpen(true);
        }
    };

    const handleNewTrainingClick = (datasetLabel: string) => {
        handleDatasetSelect(datasetLabel);
        setShowNewTrainingWizard(true);
    };

    const handleResumeTrainingClickWithSelection = (checkpointName: string) => {
        setResumeConfig(prev => ({ ...prev, checkpoint_name: checkpointName }));
        setShowResumeTrainingWizard(true);
    };

    const metrics: TrainingMetrics = trainingStatus.metrics || {};
    const history: TrainingHistoryPoint[] = trainingStatus.history || [];
    const hasAccuracyMetric = history.some((entry) =>
        typeof entry.accuracy === 'number' || typeof entry.val_accuracy === 'number'
    ) || typeof metrics.accuracy === 'number' || typeof metrics.val_accuracy === 'number';
    const metricKey = hasAccuracyMetric ? 'accuracy' : 'masked_r2';
    const valMetricKey = hasAccuracyMetric ? 'val_accuracy' : 'val_masked_r2';
    const metricLabel = hasAccuracyMetric ? 'ACC' : 'R2';
    const metricTitle = hasAccuracyMetric ? 'ACCURACY' : 'R2 SCORE';
    const metricAsPercent = hasAccuracyMetric;
    const hasHistory = history.length > 0;

    const appendTrainingLog = useCallback((message: string) => {
        setTrainingStatus((prev) => ({
            ...prev,
            log: [...(prev.log || []), message],
        }));
    }, []);

    const { runTrainingAction } = useTrainingActionRunner({
        setLoading: setIsLoading,
        appendLog: appendTrainingLog,
    });

    const handleConfirmTraining = useCallback(async () => {
        const trainingConfig = {
            ...config,
            dataset_label: selectedDatasetLabel || undefined,
            dataset_hash: selectedDatasetHash || undefined,
        };
        await runTrainingAction({
            action: () => startTraining(trainingConfig),
            successStatus: 'started',
            actionLabel: 'start training',
            onSuccess: (result) => {
                setShowNewTrainingWizard(false);
                startPolling(result.poll_interval ?? 1.0);
                checkStatus();
                setActiveView('dashboard');
            },
        });
    }, [checkStatus, config, runTrainingAction, selectedDatasetHash, selectedDatasetLabel, startPolling]);

    const handleDatasetSelect = useCallback((label: string) => {
        setSelectedDatasetLabel(label);
        const match = processedDatasets.find((dataset) => dataset.dataset_label === label);
        setSelectedDatasetHash(match?.dataset_hash ?? null);
    }, [processedDatasets]);

    const handleConfirmResume = useCallback(async () => {
        await runTrainingAction({
            action: () => resumeTraining(resumeConfig),
            successStatus: 'started',
            actionLabel: 'resume training',
            onSuccess: (result) => {
                setShowResumeTrainingWizard(false);
                startPolling(result.poll_interval ?? 1.0);
                checkStatus();
                setActiveView('dashboard');
            },
        });
    }, [checkStatus, resumeConfig, runTrainingAction, startPolling]);

    const handleStopTraining = useCallback(async () => {
        await runTrainingAction({
            action: () => stopTraining(),
            successStatus: 'stopped',
            actionLabel: 'stop training',
            onSuccess: () => {
                checkStatus();
            },
        });
    }, [checkStatus, runTrainingAction]);

    const activeSpec = useMemo(
        () => TRAINING_VIEWS.find((view) => view.id === activeView) || TRAINING_VIEWS[0],
        [activeView]
    );

    const dashboardWidget = (
        <div className="training-dashboard">
            <div className="dashboard-header">
                <div className="dashboard-title">
                    <span className="dashboard-icon">*</span>
                    <span>Training Dashboard</span>
                </div>
                <span className={`training-status-badge ${trainingStatus.is_training ? 'active' : 'idle'}`}>
                    {trainingStatus.is_training ? 'Training in Progress' : 'Idle'}
                </span>
            </div>

            <div className="metrics-row">
                <MetricCard
                    label="EPOCH"
                    value={`${trainingStatus.current_epoch} / ${trainingStatus.total_epochs || config.epochs}`}
                    color="var(--slate-800)"
                />
                <MetricCard
                    label="TRAIN LOSS"
                    icon="v"
                    value={formatLossValue(metrics.loss)}
                    color={CHART_COLORS.loss}
                />
                <MetricCard
                    label="VAL LOSS"
                    icon="v"
                    value={formatLossValue(metrics.val_loss)}
                    color={CHART_COLORS.valLoss}
                />
                <MetricCard
                    label={`TRAIN ${metricLabel}`}
                    icon="o"
                    value={formatMetricValue(metrics[metricKey], metricAsPercent)}
                    color={CHART_COLORS.metric}
                />
                <MetricCard
                    label={`VAL ${metricLabel}`}
                    icon="o"
                    value={formatMetricValue(metrics[valMetricKey], metricAsPercent)}
                    color={CHART_COLORS.valMetric}
                />
            </div>

            <div className="dashboard-progress">
                <div className="progress-label">
                    <span>% Progress: {Math.round(trainingStatus.progress)}%</span>
                </div>
                <div className="progress-bar-wrapper">
                    <div className="progress-bar-container">
                        <div
                            className="progress-bar-fill"
                            style={{ width: `${trainingStatus.progress}%` }}
                        />
                    </div>
                    <button
                        className="stop-btn"
                        onClick={handleStopTraining}
                        disabled={!trainingStatus.is_training || isLoading}
                        type="button"
                    >
                        Stop Training
                    </button>
                </div>
            </div>

            <div className="charts-container">
                <TrainingHistoryChartPanel
                    title="LOSS"
                    hasHistory={hasHistory}
                    history={history}
                    primaryLine={{
                        dataKey: 'loss',
                        color: CHART_COLORS.loss,
                        name: 'Train Loss',
                    }}
                    secondaryLine={{
                        dataKey: 'val_loss',
                        color: CHART_COLORS.valLoss,
                        name: 'Val Loss',
                    }}
                    placeholderHint="Loss metrics will appear once training starts."
                />
                <TrainingHistoryChartPanel
                    title={metricTitle}
                    hasHistory={hasHistory}
                    history={history}
                    primaryLine={{
                        dataKey: metricKey,
                        color: CHART_COLORS.metric,
                        name: `Train ${metricLabel}`,
                    }}
                    secondaryLine={{
                        dataKey: valMetricKey,
                        color: CHART_COLORS.valMetric,
                        name: `Val ${metricLabel}`,
                    }}
                    placeholderHint="Validation metrics will appear once training starts."
                    yAxisDomain={metricAsPercent ? [0, 1] : ['auto', 'auto']}
                />
            </div>

            <div className="log-panel">
                <div className="log-header">
                    <span>Training Log</span>
                    <button
                        className="ghost-button"
                        onClick={() => setTrainingStatus(prev => ({ ...prev, log: ['Ready to start training...'] }))}
                        type="button"
                    >
                        Clear
                    </button>
                </div>
                <pre className="training-log-light" ref={logContainerRef}>
                    {(trainingStatus.log || []).join('\n')}
                </pre>
            </div>
        </div>
    );

    const renderActiveWidget = () => {
        if (activeView === 'processing') {
            return <DatasetBuilderCard onDatasetBuilt={loadProcessedDatasets} showSectionHeading={false} />;
        }
        if (activeView === 'datasets') {
            return (
                <TrainingSetupRow
                    onNewTrainingClick={handleNewTrainingClick}
                    onResumeTrainingClick={handleResumeTrainingClickWithSelection}
                    datasetAvailable={processedDatasets.length > 0}
                    checkpointsAvailable={checkpoints.length > 0}
                    processedDatasets={processedDatasets}
                    checkpoints={checkpoints}
                    isTraining={trainingStatus.is_training}
                    onDeleteDataset={handleDeleteDataset}
                    onViewDatasetMetadata={handleViewDatasetMetadata}
                    onDeleteCheckpoint={handleDeleteCheckpoint}
                    onViewCheckpointDetails={handleViewCheckpointDetails}
                    onRefreshDatasets={loadProcessedDatasets}
                    onRefreshCheckpoints={loadCheckpoints}
                    viewMode="datasets"
                    showSectionHeading={false}
                />
            );
        }
        if (activeView === 'checkpoints') {
            return (
                <TrainingSetupRow
                    onNewTrainingClick={handleNewTrainingClick}
                    onResumeTrainingClick={handleResumeTrainingClickWithSelection}
                    datasetAvailable={processedDatasets.length > 0}
                    checkpointsAvailable={checkpoints.length > 0}
                    processedDatasets={processedDatasets}
                    checkpoints={checkpoints}
                    isTraining={trainingStatus.is_training}
                    onDeleteDataset={handleDeleteDataset}
                    onViewDatasetMetadata={handleViewDatasetMetadata}
                    onDeleteCheckpoint={handleDeleteCheckpoint}
                    onViewCheckpointDetails={handleViewCheckpointDetails}
                    onRefreshDatasets={loadProcessedDatasets}
                    onRefreshCheckpoints={loadCheckpoints}
                    viewMode="checkpoints"
                    showSectionHeading={false}
                />
            );
        }

        return dashboardWidget;
    };

    return (
        <div className="ml-page training-workspace">
            <aside className="training-view-toolbar" aria-label="Training views">
                {TRAINING_VIEWS.map((view) => (
                    <button
                        key={view.id}
                        type="button"
                        className={`training-view-tab ${activeView === view.id ? 'active' : ''}`}
                        onClick={() => setActiveView(view.id)}
                        title={view.label}
                    >
                        <span className="training-view-tab-icon" aria-hidden="true">{view.icon}</span>
                        <span className="training-view-tab-label">{view.label}</span>
                    </button>
                ))}
            </aside>

            <section className="training-view-panel">
                <div className="training-view-description">
                    <h2>{activeSpec.label}</h2>
                    <p>{activeSpec.description}</p>
                </div>
                <div className="training-view-widget">
                    {renderActiveWidget()}
                </div>
            </section>

            {showNewTrainingWizard && (
                <NewTrainingWizard
                    config={config}
                    onConfigChange={setConfig}
                    onClose={() => setShowNewTrainingWizard(false)}
                    onConfirm={handleConfirmTraining}
                    isLoading={isLoading}
                    selectedDatasetLabel={selectedDatasetLabel || ''}
                />
            )}

            {showResumeTrainingWizard && (
                <ResumeTrainingWizard
                    checkpoints={checkpoints}
                    config={resumeConfig}
                    onConfigChange={setResumeConfig}
                    onClose={() => setShowResumeTrainingWizard(false)}
                    onConfirm={handleConfirmResume}
                    isLoading={isLoading}
                    selectedCheckpointName={resumeConfig.checkpoint_name}
                />
            )}

            <InfoModal
                isOpen={infoModalOpen}
                onClose={() => setInfoModalOpen(false)}
                title={infoModalTitle}
                data={infoModalData}
            />
        </div>
    );
};

export default MachineLearningPage;

// app/ml_client/src/app/features/training/pages/machine-learning-page.component.ts
import { Component, computed, effect, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { ActivatedRoute } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { map } from 'rxjs';
import { TrainingViewId, TrainingWorkspaceStore } from '../../../core/state/training-workspace.store';
import { InfoModalComponent } from '../../../shared/components/info-modal/info-modal.component';
import { MetricCardComponent } from '../../../shared/components/metric-card/metric-card.component';
import { DatasetBuilderCardComponent } from '../components/dataset-builder-card.component';
import { NewTrainingWizardComponent } from '../components/new-training-wizard.component';
import { ResumeTrainingWizardComponent } from '../components/resume-training-wizard.component';
import { TrainingHistoryChartPanelComponent } from '../components/training-history-chart-panel.component';
import { TrainingSetupRowComponent } from '../components/training-setup-row.component';
import { TrainingActionRunnerService } from '../services/training-action-runner.service';
import { TrainingStatusPollingService } from '../services/training-status-polling.service';
import type {
    CheckpointFullDetails,
    DatasetFullInfo,
    TrainingHistoryPoint,
    TrainingMetricKey,
    TrainingMetrics,
} from '../../../models/training.model';

interface TrainingViewSpec {
    id: TrainingViewId;
    label: string;
    description: string;
}

const TRAINING_VIEWS: readonly TrainingViewSpec[] = [
    { id: 'processing', label: 'Data Processing', description: 'Prepare adsorption datasets for model training.' },
    { id: 'datasets', label: 'Train datasets', description: 'Choose a processed dataset and configure a new training run.' },
    { id: 'checkpoints', label: 'Checkpoints', description: 'Review saved checkpoints and resume a training run.' },
    { id: 'dashboard', label: 'Training Dashboard', description: 'Track training progress, metrics, and logs in real time.' },
];

const isTrainingViewId = (value: string | null): value is TrainingViewId =>
    value === 'processing' || value === 'datasets' || value === 'checkpoints' || value === 'dashboard';

@Component({
    selector: 'adsmod-machine-learning-page',
    standalone: true,
    imports: [
        RouterLink,
        RouterLinkActive,
        DatasetBuilderCardComponent,
        TrainingSetupRowComponent,
        NewTrainingWizardComponent,
        ResumeTrainingWizardComponent,
        InfoModalComponent,
        MetricCardComponent,
        TrainingHistoryChartPanelComponent,
    ],
    template: `
        <main class="training-workspace">
            <section class="training-view-toolbar" aria-label="Training views">
                @for (view of views; track view.id) {
                    <a class="training-view-tab" [routerLink]="['/training', view.id]" routerLinkActive="active">
                        <span class="training-view-tab-icon" aria-hidden="true">
                            @switch (view.id) {
                                @case ('processing') {
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                                        <polyline points="7 10 12 15 17 10" />
                                        <line x1="12" y1="15" x2="12" y2="3" />
                                    </svg>
                                }
                                @case ('datasets') {
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                                        <rect x="3" y="4" width="18" height="6" rx="1" />
                                        <rect x="3" y="14" width="18" height="6" rx="1" />
                                        <line x1="7" y1="7" x2="7.01" y2="7" />
                                        <line x1="7" y1="17" x2="7.01" y2="17" />
                                    </svg>
                                }
                                @case ('checkpoints') {
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                                        <rect x="4" y="4" width="16" height="16" rx="2" />
                                        <path d="M8 9h8" />
                                        <path d="M8 13h8" />
                                        <path d="M8 17h5" />
                                    </svg>
                                }
                                @case ('dashboard') {
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                                        <path d="M3 3v18h18" />
                                        <path d="M19 9l-5 5-4-4-3 3" />
                                    </svg>
                                }
                            }
                        </span>
                        <span class="training-view-tab-label">{{ view.label }}</span>
                    </a>
                }
            </section>

            <section class="training-view-panel">
                <div class="training-view-description">
                    <h2>{{ activeView().label }}</h2>
                    <p>{{ activeView().description }}</p>
                </div>

                @switch (activeView().id) {
                    @case ('processing') {
                        <div class="training-view-widget">
                            <adsmod-dataset-builder-card
                                [showSectionHeading]="false"
                                [datasetBuilt]="refreshWorkspaceFn"
                                [workspaceChanged]="refreshWorkspaceFn"
                            />
                        </div>
                    }
                    @case ('datasets') {
                        <div class="training-view-widget">
                            <adsmod-training-setup-row
                                [processedDatasets]="store.processedDatasets()"
                                [checkpoints]="store.checkpoints()"
                                [isTraining]="store.trainingStatus().is_training"
                                [onRefreshDatasets]="refreshDatasetsFn"
                                [onRefreshCheckpoints]="refreshCheckpointsFn"
                                viewMode="datasets"
                                [showSectionHeading]="false"
                                (newTrainingRequested)="openNewTrainingWizard($event)"
                                (resumeTrainingRequested)="openResumeTrainingWizard($event)"
                                (datasetMetadataRequested)="viewDatasetMetadata($event)"
                                (datasetDeleteRequested)="deleteDataset($event)"
                                (checkpointDetailsRequested)="viewCheckpointDetails($event)"
                                (checkpointDeleteRequested)="deleteCheckpoint($event)"
                            />
                        </div>
                    }
                    @case ('checkpoints') {
                        <div class="training-view-widget">
                            <adsmod-training-setup-row
                                [processedDatasets]="store.processedDatasets()"
                                [checkpoints]="store.checkpoints()"
                                [isTraining]="store.trainingStatus().is_training"
                                [onRefreshDatasets]="refreshDatasetsFn"
                                [onRefreshCheckpoints]="refreshCheckpointsFn"
                                viewMode="checkpoints"
                                [showSectionHeading]="false"
                                (newTrainingRequested)="openNewTrainingWizard($event)"
                                (resumeTrainingRequested)="openResumeTrainingWizard($event)"
                                (datasetMetadataRequested)="viewDatasetMetadata($event)"
                                (datasetDeleteRequested)="deleteDataset($event)"
                                (checkpointDetailsRequested)="viewCheckpointDetails($event)"
                                (checkpointDeleteRequested)="deleteCheckpoint($event)"
                            />
                        </div>
                    }
                    @case ('dashboard') {
                        <div class="training-view-widget training-dashboard">
                            <div class="dashboard-header">
                                <div class="dashboard-title">
                                    <span class="dashboard-icon" aria-hidden="true">
                                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M3 17l6-6 4 4 8-8" />
                                            <path d="M15 7h6v6" />
                                        </svg>
                                    </span>
                                    <span>Training Dashboard</span>
                                </div>
                                <span class="training-status-badge" [class.active]="store.trainingStatus().is_training" [class.idle]="!store.trainingStatus().is_training">
                                    {{ store.trainingStatus().is_training ? 'Training in Progress' : 'Idle' }}
                                </span>
                            </div>

                            <div class="metrics-row">
                                <adsmod-metric-card label="EPOCH" [value]="epochMetric()" color="var(--slate-800)" />
                                <adsmod-metric-card label="TRAIN LOSS" [value]="trainLossMetric()" [color]="chartColors.loss" />
                                <adsmod-metric-card label="VAL LOSS" [value]="valLossMetric()" [color]="chartColors.valLoss" />
                                <adsmod-metric-card [label]="'TRAIN ' + metricLabel()" [value]="trainMetricValue()" [color]="chartColors.metric" />
                                <adsmod-metric-card [label]="'VAL ' + metricLabel()" [value]="valMetricValue()" [color]="chartColors.valMetric" />
                            </div>

                            <div class="dashboard-progress">
                                <div class="progress-label">
                                    <span>% Progress: {{ roundedProgress() }}%</span>
                                </div>
                                <div class="progress-bar-wrapper">
                                    <div class="progress-bar-container">
                                        <div class="progress-bar-fill" [style.width.%]="store.trainingStatus().progress"></div>
                                    </div>
                                    <button class="stop-btn" type="button" [disabled]="!store.trainingStatus().is_training || store.actionLoading()" (click)="stopTraining()">
                                        Stop Training
                                    </button>
                                </div>
                            </div>

                            <div class="charts-container">
                                <adsmod-training-history-chart-panel
                                    title="LOSS"
                                    [hasHistory]="hasHistory()"
                                    [history]="history()"
                                    [primaryLine]="lossPrimaryLine"
                                    [secondaryLine]="lossSecondaryLine"
                                    placeholderHint="Loss metrics will appear once training starts."
                                />
                                <adsmod-training-history-chart-panel
                                    [title]="metricTitle()"
                                    [hasHistory]="hasHistory()"
                                    [history]="history()"
                                    [primaryLine]="metricPrimaryLine()"
                                    [secondaryLine]="metricSecondaryLine()"
                                    placeholderHint="Validation metrics will appear once training starts."
                                    [yAxisDomain]="metricAxisDomain()"
                                />
                            </div>

                            <div class="log-panel">
                                <div class="log-header">
                                    <span>Training Log</span>
                                    <button class="ghost-button" type="button" (click)="store.clearTrainingLog()">Clear</button>
                                </div>
                                <pre class="training-log-light">{{ trainingLog() }}</pre>
                            </div>
                        </div>
                    }
                }
            </section>

            @if (store.showNewTrainingWizard()) {
                <adsmod-new-training-wizard
                    [initialConfig]="store.config()"
                    [selectedDatasetLabel]="store.selectedDatasetLabel() || ''"
                    [isLoading]="store.actionLoading()"
                    (closed)="store.closeNewTrainingWizard()"
                    (confirmed)="confirmTraining($event)"
                />
            }

            @if (store.showResumeTrainingWizard()) {
                <adsmod-resume-training-wizard
                    [checkpoints]="store.checkpoints()"
                    [selectedCheckpointName]="store.resumeConfig().checkpoint_name"
                    [initialConfig]="store.resumeConfig()"
                    [isLoading]="store.actionLoading()"
                    (closed)="store.closeResumeTrainingWizard()"
                    (confirmed)="confirmResume($event)"
                />
            }

            <adsmod-info-modal
                [isOpen]="store.infoModalOpen()"
                [title]="store.infoModalTitle()"
                [data]="store.infoModalData()"
                (closed)="store.closeInfoModal()"
            />
        </main>
    `,
})
export class MachineLearningPageComponent {
    private readonly route = inject(ActivatedRoute);
    protected readonly store = inject(TrainingWorkspaceStore);
    private readonly actionRunner = inject(TrainingActionRunnerService);
    private readonly statusPolling = inject(TrainingStatusPollingService);
    protected readonly views = TRAINING_VIEWS;
    protected readonly chartColors = {
        loss: '#f59e0b',
        valLoss: '#2563eb',
        metric: '#16a34a',
        valMetric: '#9333ea',
    };
    protected readonly lossPrimaryLine = { dataKey: 'loss', color: this.chartColors.loss, name: 'Train Loss' } as const;
    protected readonly lossSecondaryLine = { dataKey: 'val_loss', color: this.chartColors.valLoss, name: 'Val Loss' } as const;
    protected readonly refreshWorkspaceFn = () => void this.store.refreshWorkspace();
    protected readonly refreshDatasetsFn = () => void this.store.loadProcessedDatasets();
    protected readonly refreshCheckpointsFn = () => void this.store.loadCheckpoints();
    private readonly routeView = toSignal(
        this.route.paramMap.pipe(map((params) => params.get('view'))),
        { initialValue: 'processing' }
    );
    protected readonly activeView = computed(() => {
        const viewId = this.routeView();
        return TRAINING_VIEWS.find((view) => view.id === (isTrainingViewId(viewId) ? viewId : 'processing')) || TRAINING_VIEWS[0];
    });
    protected readonly dashboardStatus = computed(() => {
        const status = this.store.trainingStatus();
        if (this.store.trainingStatusError()) {
            return this.store.trainingStatusError();
        }
        return status.is_training
            ? `Training epoch ${status.current_epoch} of ${status.total_epochs}.`
            : 'No training run is currently active.';
    });
    protected readonly metrics = computed<TrainingMetrics>(() => this.store.trainingStatus().metrics || {});
    protected readonly history = computed<TrainingHistoryPoint[]>(() => this.store.trainingStatus().history || []);
    protected readonly hasAccuracyMetric = computed(() =>
        this.history().some((entry) => typeof entry.accuracy === 'number' || typeof entry.val_accuracy === 'number')
        || typeof this.metrics().accuracy === 'number'
        || typeof this.metrics().val_accuracy === 'number'
    );
    protected readonly metricKey = computed(() => this.hasAccuracyMetric() ? 'accuracy' : 'masked_r2');
    protected readonly valMetricKey = computed(() => this.hasAccuracyMetric() ? 'val_accuracy' : 'val_masked_r2');
    protected readonly metricLabel = computed(() => this.hasAccuracyMetric() ? 'ACC' : 'R2');
    protected readonly metricTitle = computed(() => this.hasAccuracyMetric() ? 'ACCURACY' : 'R2 SCORE');
    protected readonly metricAxisDomain = computed<[number, number] | ['auto', 'auto']>(() => this.hasAccuracyMetric() ? [0, 1] : ['auto', 'auto']);
    protected readonly hasHistory = computed(() => this.history().length > 0);
    protected readonly epochMetric = computed(() => `${this.store.trainingStatus().current_epoch} / ${this.store.trainingStatus().total_epochs || this.store.config().epochs}`);
    protected readonly trainLossMetric = computed(() => this.formatLossValue(this.metrics().loss));
    protected readonly valLossMetric = computed(() => this.formatLossValue(this.metrics().val_loss));
    protected readonly trainMetricValue = computed(() => this.formatMetricValue(this.metrics()[this.metricKey()], this.hasAccuracyMetric()));
    protected readonly valMetricValue = computed(() => this.formatMetricValue(this.metrics()[this.valMetricKey()], this.hasAccuracyMetric()));
    protected readonly roundedProgress = computed(() => Math.round(this.store.trainingStatus().progress));
    protected readonly trainingLog = computed(() => (this.store.trainingStatus().log || []).join('\n'));
    protected readonly metricPrimaryLine = computed(() => ({
        dataKey: this.metricKey() as TrainingMetricKey,
        color: this.chartColors.metric,
        name: `Train ${this.metricLabel()}`,
    }));
    protected readonly metricSecondaryLine = computed(() => ({
        dataKey: this.valMetricKey() as TrainingMetricKey,
        color: this.chartColors.valMetric,
        name: `Val ${this.metricLabel()}`,
    }));

    constructor() {
        effect(() => {
            this.store.setActiveView(this.activeView().id);
        });
        void this.statusPolling.checkStatus(
            (status) => this.store.setTrainingStatus(status),
            (error) => this.store.trainingStatusError.set(error),
            () => void this.store.loadCheckpoints()
        );
    }

    protected async refreshStatus(): Promise<void> {
        await this.statusPolling.checkStatus(
            (status) => this.store.setTrainingStatus(status),
            (error) => this.store.trainingStatusError.set(error),
            () => void this.store.loadCheckpoints()
        );
    }

    protected openNewTrainingWizard(datasetLabel: string): void {
        this.store.showNewTrainingWizardFor(datasetLabel);
    }

    protected openResumeTrainingWizard(checkpointName: string): void {
        this.store.showResumeTrainingWizardFor(checkpointName);
    }

    protected async confirmTraining(config: import('../../../models/training.model').TrainingConfig): Promise<void> {
        this.store.setConfig(config);
        await this.actionRunner.runTrainingAction({
            action: () => this.store.startTraining(),
            successStatus: 'started',
            actionLabel: 'start training',
            setLoading: (loading) => this.store.setActionLoading(loading),
            appendLog: (message) => this.store.appendTrainingLog(message),
            onSuccess: async (result) => {
                this.store.closeNewTrainingWizard();
                this.statusPolling.startPolling(
                    result.poll_interval,
                    (status) => this.store.setTrainingStatus(status),
                    (error) => this.store.trainingStatusError.set(error),
                    () => void this.store.loadCheckpoints()
                );
                await this.refreshStatus();
                this.store.setActiveView('dashboard');
            },
        });
    }

    protected async confirmResume(config: import('../../../models/training.model').ResumeTrainingConfig): Promise<void> {
        this.store.setResumeConfig(config);
        await this.actionRunner.runTrainingAction({
            action: () => this.store.resumeTraining(),
            successStatus: 'started',
            actionLabel: 'resume training',
            setLoading: (loading) => this.store.setActionLoading(loading),
            appendLog: (message) => this.store.appendTrainingLog(message),
            onSuccess: async (result) => {
                this.store.closeResumeTrainingWizard();
                this.statusPolling.startPolling(
                    result.poll_interval,
                    (status) => this.store.setTrainingStatus(status),
                    (error) => this.store.trainingStatusError.set(error),
                    () => void this.store.loadCheckpoints()
                );
                await this.refreshStatus();
                this.store.setActiveView('dashboard');
            },
        });
    }

    protected async stopTraining(): Promise<void> {
        await this.actionRunner.runTrainingAction({
            action: () => this.store.stopTraining(),
            successStatus: 'stopped',
            actionLabel: 'stop training',
            setLoading: (loading) => this.store.setActionLoading(loading),
            appendLog: (message) => this.store.appendTrainingLog(message),
            onSuccess: async () => {
                await this.refreshStatus();
            },
        });
    }

    protected async deleteDataset(label: string): Promise<void> {
        if (!window.confirm(`Are you sure you want to delete dataset '${label}'?`)) {
            return;
        }
        const result = await this.store.deleteProcessedDataset(label);
        if (result.success) {
            await this.store.loadProcessedDatasets();
        } else {
            this.store.openErrorModal('Delete Dataset Failed', result.message || 'Failed to delete dataset.');
        }
    }

    protected async viewDatasetMetadata(label: string): Promise<void> {
        this.store.setActionLoading(true);
        const info = await this.store.fetchDatasetMetadata(label);
        this.store.setActionLoading(false);
        if (info && info.available) {
            this.store.openInfoModal('Dataset Metadata', this.buildDatasetMetadataModalData(info));
        } else {
            this.store.openErrorModal('Dataset Metadata', `Could not fetch details for dataset '${label}'.`);
        }
    }

    protected async deleteCheckpoint(name: string): Promise<void> {
        if (!window.confirm(`Are you sure you want to delete checkpoint '${name}'?`)) {
            return;
        }
        const result = await this.store.deleteCheckpoint(name);
        if (result.success) {
            await this.store.loadCheckpoints();
        } else {
            this.store.openErrorModal('Delete Checkpoint Failed', result.error || 'Failed to delete checkpoint.');
        }
    }

    protected async viewCheckpointDetails(name: string): Promise<void> {
        const { details, error } = await this.store.fetchCheckpointDetails(name);
        if (error) {
            this.store.openErrorModal('Checkpoint Details', error);
        } else if (details) {
            this.store.openInfoModal('Checkpoint Details', this.buildCheckpointDetailsModalData(details));
        }
    }

    private formatLossValue(value: number | undefined): string {
        const safeValue = typeof value === 'number' ? value : 0;
        return safeValue.toFixed(4);
    }

    private formatMetricValue(value: number | undefined, asPercent: boolean): string {
        const safeValue = typeof value === 'number' ? value : 0;
        if (asPercent) {
            return `${(safeValue * 100).toFixed(2)}%`;
        }
        return safeValue.toFixed(4);
    }

    private buildDatasetMetadataModalData(info: DatasetFullInfo) {
        return {
            'Dataset Label': info.dataset_label,
            'Created At': info.created_at,
            'Total Samples': info.total_samples,
            'Train Samples': info.train_samples,
            'Validation Samples': info.validation_samples,
            'Sample Fraction': info.sample_size,
            'Validation Fraction': info.validation_size,
            'Min Measurements': info.min_measurements,
            'Max Measurements': info.max_measurements,
            'SMILES Length': info.smile_sequence_size,
            'Max Pressure': info.max_pressure,
            'Max Uptake': info.max_uptake,
            'SMILES Vocabulary': info.smile_vocabulary_size,
            'Adsorbents Count': info.adsorbent_vocabulary_size,
            Normalization: info.normalization_stats,
        };
    }

    private buildCheckpointDetailsModalData(details: CheckpointFullDetails) {
        return {
            Name: details.name,
            'Epochs Trained': details.epochs_trained,
            'Final Loss': details.final_loss?.toFixed(6) ?? 'N/A',
            'Is Compatible': details.is_compatible ? 'Yes' : 'No',
            'Created At': details.created_at || 'Unknown',
        };
    }
}
