// app/client/src/app/features/fitting/models-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { ADSORPTION_MODELS } from '../../core/constants/adsorption-models';
import { CoreWorkspaceStore, OptimizationMethod } from '../../core/state/core-workspace.store';
import { HeaderTabsComponent } from '../../layout/header-tabs.component';
import type { ModelParameters } from '../../models/fitting.model';
import { NumberInputComponent } from '../../shared/components/number-input/number-input.component';
import { ModelCardComponent } from './model-card.component';

interface OptimizationMethodOption {
    value: OptimizationMethod;
    label: string;
}

const OPTIMIZATION_METHOD_OPTIONS: readonly OptimizationMethodOption[] = [
    { value: 'LSS', label: 'Least Squares (LSS)' },
    { value: 'BFGS', label: 'BFGS' },
    { value: 'L-BFGS-B', label: 'L-BFGS-B' },
    { value: 'Nelder-Mead', label: 'Nelder-Mead' },
    { value: 'Powell', label: 'Powell' },
];

const parseOptimizationMethod = (value: string): OptimizationMethod | null => {
    const option = OPTIMIZATION_METHOD_OPTIONS.find((candidate) => candidate.value === value);
    return option?.value ?? null;
};

@Component({
    selector: 'adsmod-models-page',
    standalone: true,
    imports: [ModelCardComponent, NumberInputComponent, HeaderTabsComponent],
    template: `
        <div class="route-workspace route-workspace-fitting">
            <aside class="route-rail route-rail-fitting" aria-label="Fitting overview">
                <div class="route-rail-brand">
                    <div class="route-rail-logo" aria-hidden="true">AD</div>
                    <div class="route-rail-wordmark">ADSMOD</div>
                </div>
                <div class="route-rail-copy">
                    <h1>Fitting</h1>
                    <p>Configure the optimizer and run the fit.</p>
                </div>
            </aside>

            <section class="route-canvas route-canvas-fitting">
                <div class="route-tabs-row">
                    <adsmod-header-tabs />
                </div>

                <div class="models-page">
                    <div class="fitting-config-panel">
                        <div class="models-header-row">
                            <div class="models-title-block">
                                <h3>Fitting Configuration</h3>
                            </div>
                        </div>

                        <div class="fitting-main-layout">
                            <div class="fitting-controls-column">
                                <div class="fitting-controls-row">
                                    <div class="control-group">
                                        <label class="field-label">Dataset</label>
                                        <div class="fitting-dataset-row">
                                            <select
                                                [value]="store.selectedDataset() || ''"
                                                (change)="selectDataset($event)"
                                                class="select-input fitting-dataset-select"
                                            >
                                                <option value="">{{ store.availableDatasets().length === 0 ? 'No datasets available' : 'Select a dataset' }}</option>
                                                <option [value]="store.nistDatasetOption">NIST-A Collection</option>
                                                @for (datasetName of store.availableDatasets(); track datasetName) {
                                                    <option [value]="datasetName">{{ datasetName }}</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <adsmod-number-input
                                            label="Max iterations"
                                            [value]="store.maxIterations()"
                                            [min]="1"
                                            [max]="1000000"
                                            [step]="1"
                                            [precision]="0"
                                            (valueChange)="store.setMaxIterations($event)"
                                        />
                                    </div>
                                    <div class="control-group">
                                        <label class="field-label">Optimization method</label>
                                        <select
                                            [value]="store.optimizationMethod()"
                                            (change)="selectOptimizer($event)"
                                            class="select-input"
                                        >
                                            @for (option of optimizationOptions; track option.value) {
                                                <option [value]="option.value">{{ option.label }}</option>
                                            }
                                        </select>
                                    </div>
                                    <div class="control-group">
                                        <div class="fitting-action-buttons">
                                            <button class="primary fitting-action-primary" type="button" (click)="startFitting()">
                                                Start Fitting
                                            </button>
                                            <button class="secondary fitting-action-secondary" type="button" (click)="store.resetFittingStatus()">
                                                Reset Log
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="fitting-status-column">
                                <div class="fitting-status-box">
                                    <div class="status-label">Fitting Log:</div>
                                    <pre class="status-text">{{ store.fittingStatus() || 'Ready to start...' }}</pre>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr class="section-separator" />

                    <div class="models-grid-header">
                        <h3>Select Adsorption Models</h3>
                    </div>

                    <div class="models-grid">
                        @for (model of models; track model.id) {
                            <adsmod-model-card
                                [model]="model"
                                [isExpanded]="expandedModel() === model.id"
                                [isEnabled]="store.modelStates()[model.name].enabled"
                                [currentConfig]="store.modelStates()[model.name].config"
                                (toggle)="toggleExpanded($event)"
                                (enabledChange)="store.setModelEnabled(model.name, $event)"
                                (configChange)="updateModelConfig(model.name, $event)"
                            />
                        }
                    </div>
                </div>
            </section>
        </div>
    `,
})
export class ModelsPageComponent {
    protected readonly store = inject(CoreWorkspaceStore);
    protected readonly models = ADSORPTION_MODELS;
    protected readonly optimizationOptions = OPTIMIZATION_METHOD_OPTIONS;
    protected readonly expandedModel = signal<string | null>(null);

    protected toggleExpanded(modelId: string): void {
        this.expandedModel.set(this.expandedModel() === modelId ? null : modelId);
    }

    protected selectDataset(event: Event): void {
        const select = event.target as HTMLSelectElement;
        this.store.setSelectedDataset(select.value);
    }

    protected selectOptimizer(event: Event): void {
        const select = event.target as HTMLSelectElement;
        const method = parseOptimizationMethod(select.value);
        if (method) {
            this.store.setOptimizationMethod(method);
        }
    }

    protected updateModelConfig(modelName: string, config: ModelParameters): void {
        this.store.setModelParameters(modelName, config);
    }

    protected async startFitting(): Promise<void> {
        await this.store.startFitting();
    }
}

// ADSMOD/client/src/components/ModelsPage.tsx
import React, { useState, useCallback, useMemo } from 'react';
import { ModelCard } from './ModelCard';
import { NumberInput } from './UIComponents';
import { ADSORPTION_MODELS } from '../adsorptionModels';
import type { ModelParameters, FittingPayload } from '../types';

type OptimizationMethod = FittingPayload['optimization_method'];

interface ModelState {
    enabled: boolean;
    config: ModelParameters;
}

interface ModelsPageProps {
    modelStates: Record<string, ModelState>;
    onParametersChange: (modelName: string, parameters: ModelParameters) => void;
    onToggle: (modelName: string, enabled: boolean) => void;
    maxIterations: number;
    onMaxIterationsChange: (value: number) => void;
    optimizationMethod: OptimizationMethod;
    onOptimizationMethodChange: (value: OptimizationMethod) => void;
    fittingStatus: string;
    onStartFitting: () => void;
    onResetFittingStatus: () => void;
    availableDatasets: string[];
    selectedDataset: string | null;
    onDatasetSelect: (name: string | null) => void;
}

/**
 * ModelsPage (ModelsPanel): Container component that manages fitting configuration and 9 adsorption model cards.
 * 
 * New Structure:
 * 1. Fitting Panel: Max iterations, Method, Start/Reset buttons, Logs.
 * 2. Separator
 * 3. Models Grid: 3x3 grid of model cards.
 */
export const ModelsPage: React.FC<ModelsPageProps> = ({
    modelStates,
    onParametersChange,
    onToggle,
    maxIterations,
    onMaxIterationsChange,
    optimizationMethod,
    onOptimizationMethodChange,
    fittingStatus,
    onStartFitting,
    onResetFittingStatus,
    availableDatasets,
    selectedDataset,
    onDatasetSelect,
}) => {
    // Single expanded card strategy: only one card can be expanded at a time
    const [expandedId, setExpandedId] = useState<string | null>(null);

    // Handle card expand/collapse toggle
    const handleCardToggle = useCallback((modelId: string) => {
        setExpandedId((prev) => (prev === modelId ? null : modelId));
    }, []);

    // Handle model enabled/disabled toggle
    const handleEnabledChange = useCallback(
        (modelName: string, enabled: boolean) => {
            onToggle(modelName, enabled);
        },
        [onToggle]
    );

    // Handle configuration change
    const handleConfigChange = useCallback(
        (modelName: string, config: ModelParameters) => {
            onParametersChange(modelName, config);
        },
        [onParametersChange]
    );

    // Create a 3x3 grid (9 cells total) using the ADSORPTION_MODELS data
    const gridCells = useMemo(() => {
        return Array(9)
            .fill(null)
            .map((_, index) => {
                const model = ADSORPTION_MODELS[index];
                if (!model) {
                    return <div key={`empty-${index}`} className="model-grid-card empty" />;
                }

                const state = modelStates[model.name] || {
                    enabled: true,
                    config: {},
                };

                return (
                    <ModelCard
                        key={model.id}
                        model={model}
                        isExpanded={expandedId === model.id}
                        isEnabled={state.enabled}
                        currentConfig={state.config}
                        onToggle={handleCardToggle}
                        onEnabledChange={handleEnabledChange}
                        onConfigChange={handleConfigChange}
                    />
                );
            });
    }, [expandedId, modelStates, handleCardToggle, handleEnabledChange, handleConfigChange]);

    return (
        <div className="models-page">
            <div className="fitting-config-panel" style={{ marginBottom: '3rem' }}>
                <div className="models-header-row">
                    <div className="models-title-block">
                        <h3>Fitting Configuration</h3>
                        <p>Configure the optimizer and run the fit.</p>
                    </div>

                </div>

                <div className="fitting-main-layout" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', marginTop: '1.5rem' }}>
                    <div className="fitting-controls-column">
                        <div className="fitting-controls-row" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                            <div className="control-group">
                                <label className="field-label">Dataset</label>
                                <select
                                    value={selectedDataset || ''}
                                    onChange={(e) => onDatasetSelect(e.target.value || null)}
                                    className="select-input"
                                >
                                    <option value="">
                                        {availableDatasets.length === 0 ? 'No datasets available' : 'Select a dataset'}
                                    </option>
                                    {availableDatasets.map((name) => (
                                        <option key={name} value={name}>
                                            {name}
                                        </option>
                                    ))}
                                </select>
                            </div>
                            <div className="control-group">
                                <NumberInput
                                    label="Max iterations"
                                    value={maxIterations}
                                    onChange={onMaxIterationsChange}
                                    min={1}
                                    max={1000000}
                                    step={1}
                                    precision={0}
                                />
                            </div>
                            <div className="control-group">
                                <label className="field-label">Optimization method</label>
                                <select
                                    value={optimizationMethod}
                                    onChange={(e) => onOptimizationMethodChange(e.target.value as OptimizationMethod)}
                                    className="select-input"
                                >
                                    <option value="LSS">Least Squares (LSS)</option>
                                    <option value="BFGS">BFGS</option>
                                    <option value="L-BFGS-B">L-BFGS-B</option>
                                    <option value="Nelder-Mead">Nelder-Mead</option>
                                    <option value="Powell">Powell</option>
                                </select>
                            </div>
                            <div className="control-group">
                                <button className="primary" onClick={onStartFitting} style={{ width: '100%', justifyContent: 'center', marginBottom: '0.75rem' }}>
                                    Start Fitting
                                </button>
                                <button
                                    onClick={onResetFittingStatus}
                                    style={{
                                        width: '100%',
                                        justifyContent: 'center',
                                        padding: '0.6rem',
                                        background: 'transparent',
                                        border: '1px solid #cbd5e1',
                                        borderRadius: '6px',
                                        cursor: 'pointer',
                                        color: '#475569',
                                        fontSize: '0.9rem',
                                        fontWeight: 500
                                    }}
                                >
                                    Reset Log
                                </button>
                            </div>
                        </div>
                    </div>

                    <div className="fitting-status-box" style={{ height: '100%' }}>
                        <div className="status-label" style={{ marginBottom: '0.5rem', fontWeight: 500, color: 'var(--slate-700)' }}>Fitting Log:</div>
                        <pre className="status-text" style={{
                            height: 'calc(100% - 1.5rem)',
                            minHeight: '160px',
                            background: '#0f172a',
                            color: '#e2e8f0',
                            padding: '1rem',
                            borderRadius: 'var(--radius-md)',
                            overflow: 'auto',
                            fontFamily: 'monospace',
                            fontSize: '0.9rem'
                        }}>{fittingStatus || 'Ready to start...'}</pre>
                    </div>
                </div>
            </div>

            <hr className="section-separator" style={{ margin: '3rem 0', opacity: 0.5 }} />

            <div className="models-grid-header" style={{ marginBottom: '2rem' }}>
                <h3>Select Adsorption Models</h3>
            </div>

            <div className="models-grid">{gridCells}</div>
        </div>
    );
};

export default ModelsPage;
