// ADSMOD/client/src/components/NistCollectionRows.tsx
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
    fetchNistCategoryStatus,
    pingNistCategoryServer,
    pollNistJobUntilComplete,
    startNistCategoryEnrichJob,
    startNistCategoryFetchJob,
    startNistCategoryIndexJob,
} from '../services';
import type {
    NISTCategoryKey,
    NISTCategoryOperationResponse,
    NISTCategoryRecordStatus,
} from '../types';

interface NistCollectionRowsProps {
    onStatusUpdate: (message: string) => void;
}

interface CategoryOperationState {
    running: boolean;
    operation: 'idle' | 'index' | 'fetch' | 'enrich';
    progress: number;
}

const CATEGORY_ORDER: NISTCategoryKey[] = ['experiments', 'guest', 'host'];
const CATEGORY_LABELS: Record<NISTCategoryKey, string> = {
    experiments: 'Adsorption experiments',
    guest: 'Adsorbate species',
    host: 'Adsorbent materials',
};
const OPERATION_LABELS: Record<CategoryOperationState['operation'], string> = {
    idle: 'Idle',
    index: 'Updating index',
    fetch: 'Fetching records',
    enrich: 'Enriching properties',
};

const FRACTION_MIN = 0.001;
const FRACTION_MAX = 1.0;
const FRACTION_STEP = 0.001;

const fractionStorageKey = (category: NISTCategoryKey): string =>
    `adsmod.nist.fraction.${category}`;

const clampFraction = (value: number): number =>
    Math.min(FRACTION_MAX, Math.max(FRACTION_MIN, value));

const normalizeFraction = (value: unknown, fallback = 1.0): number => {
    if (typeof value !== 'number' || Number.isNaN(value)) {
        return fallback;
    }
    return clampFraction(Number(value.toFixed(3)));
};

const readPersistedFraction = (category: NISTCategoryKey): number => {
    if (typeof window === 'undefined') {
        return 1.0;
    }
    const rawValue = window.localStorage.getItem(fractionStorageKey(category));
    if (!rawValue) {
        return 1.0;
    }
    const parsedValue = Number.parseFloat(rawValue);
    return normalizeFraction(parsedValue, 1.0);
};

const persistFraction = (category: NISTCategoryKey, value: number): void => {
    if (typeof window === 'undefined') {
        return;
    }
    window.localStorage.setItem(fractionStorageKey(category), value.toFixed(3));
};

const formatCompactDateTime = (value: string | null): string => {
    if (!value) {
        return 'N.A.';
    }
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
        return 'N.A.';
    }
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    const hh = String(date.getHours()).padStart(2, '0');
    const min = String(date.getMinutes()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd} ${hh}:${min}`;
};

const emptyStatus = (category: NISTCategoryKey): NISTCategoryRecordStatus => ({
    category,
    local_count: 0,
    available_count: 0,
    last_update: null,
    server_ok: null,
    server_checked_at: null,
    supports_enrichment: category !== 'experiments',
});

const initialStatusMap = (): Record<NISTCategoryKey, NISTCategoryRecordStatus> => ({
    experiments: emptyStatus('experiments'),
    guest: emptyStatus('guest'),
    host: emptyStatus('host'),
});

const initialOperationMap = (): Record<NISTCategoryKey, CategoryOperationState> => ({
    experiments: { running: false, operation: 'idle', progress: 0 },
    guest: { running: false, operation: 'idle', progress: 0 },
    host: { running: false, operation: 'idle', progress: 0 },
});

const PingIcon = () => (
    <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M12 18.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Z" fill="currentColor" />
        <path d="M7.9 15.1a5.8 5.8 0 0 1 8.2 0l1.4-1.4a7.8 7.8 0 0 0-11 0l1.4 1.4Z" fill="currentColor" />
        <path d="M4.5 11.7a10.6 10.6 0 0 1 15 0l1.4-1.4a12.6 12.6 0 0 0-17.8 0l1.4 1.4Z" fill="currentColor" />
    </svg>
);

const IndexIcon = () => (
    <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M5 5h14v2H5V5Zm0 6h14v2H5v-2Zm0 6h14v2H5v-2Z" fill="currentColor" />
    </svg>
);

const DownloadIcon = () => (
    <svg viewBox="0 0 24 24" aria-hidden="true">
        <path
            d="M11 3h2v9.2l2.9-2.9 1.4 1.4-5.3 5.3-5.3-5.3 1.4-1.4 2.9 2.9V3Zm-6 14h14v4H5v-4Z"
            fill="currentColor"
        />
    </svg>
);

const EnrichIcon = () => (
    <svg viewBox="0 0 24 24" aria-hidden="true">
        <path
            d="M9 3h6v2h-1v4.2l4.7 7.8A2.3 2.3 0 0 1 16.7 21H7.3a2.3 2.3 0 0 1-2-3.5L10 9.2V5H9V3Zm2.2 8.1-4.2 7a.3.3 0 0 0 .3.4h9.4a.3.3 0 0 0 .3-.4l-4.2-7h-1.6Z"
            fill="currentColor"
        />
    </svg>
);

export const NistCollectionRows: React.FC<NistCollectionRowsProps> = ({
    onStatusUpdate,
}) => {
    const [statuses, setStatuses] = useState<Record<NISTCategoryKey, NISTCategoryRecordStatus>>(
        initialStatusMap
    );
    const [fractions, setFractions] = useState<Record<NISTCategoryKey, number>>(() => ({
        experiments: readPersistedFraction('experiments'),
        guest: readPersistedFraction('guest'),
        host: readPersistedFraction('host'),
    }));
    const [fractionInputs, setFractionInputs] = useState<Record<NISTCategoryKey, string>>(() => ({
        experiments: readPersistedFraction('experiments').toFixed(3),
        guest: readPersistedFraction('guest').toFixed(3),
        host: readPersistedFraction('host').toFixed(3),
    }));
    const [operations, setOperations] = useState<Record<NISTCategoryKey, CategoryOperationState>>(
        initialOperationMap
    );

    const loadCategoryStatus = useCallback(async () => {
        const result = await fetchNistCategoryStatus();
        if (result.error || !result.data) {
            return;
        }

        const updatedStatus = initialStatusMap();
        result.data.categories.forEach((item) => {
            updatedStatus[item.category] = item;
        });
        setStatuses(updatedStatus);
    }, []);

    useEffect(() => {
        void loadCategoryStatus();
    }, [loadCategoryStatus]);

    const commitFraction = useCallback(
        (category: NISTCategoryKey) => {
            const parsed = Number.parseFloat(fractionInputs[category]);
            const normalized = Number.isFinite(parsed)
                ? normalizeFraction(parsed, fractions[category])
                : normalizeFraction(fractions[category], 1.0);
            persistFraction(category, normalized);
            setFractions((previous) => ({ ...previous, [category]: normalized }));
            setFractionInputs((previous) => ({
                ...previous,
                [category]: normalized.toFixed(3),
            }));
        },
        [fractionInputs, fractions]
    );

    const handleFractionInput = useCallback((category: NISTCategoryKey, value: string) => {
        setFractionInputs((previous) => ({ ...previous, [category]: value }));
        const parsed = Number.parseFloat(value);
        if (!Number.isFinite(parsed)) {
            return;
        }
        const normalized = normalizeFraction(parsed, 1.0);
        setFractions((previous) => ({ ...previous, [category]: normalized }));
    }, []);

    const setCategoryOperation = useCallback(
        (
            category: NISTCategoryKey,
            update: Partial<CategoryOperationState>
        ) => {
            setOperations((previous) => ({
                ...previous,
                [category]: { ...previous[category], ...update },
            }));
        },
        []
    );

    const finalizeCategoryOperation = useCallback((category: NISTCategoryKey) => {
        setCategoryOperation(category, {
            running: false,
            operation: 'idle',
            progress: 0,
        });
    }, [setCategoryOperation]);

    const runCategoryJob = useCallback(async (
        category: NISTCategoryKey,
        operation: CategoryOperationState['operation'],
        startJob: () => Promise<{ jobId: string | null; pollInterval?: number; error: string | null }>,
        onSuccess: (result: NISTCategoryOperationResponse) => void
    ) => {
        if (operations[category].running) {
            return;
        }

        setCategoryOperation(category, { running: true, operation, progress: 0 });
        try {
            const started = await startJob();
            if (started.error || !started.jobId) {
                onStatusUpdate(`[ERROR] ${CATEGORY_LABELS[category]}: ${started.error || 'Unable to start job.'}`);
                return;
            }

            const finished = await pollNistJobUntilComplete(
                started.jobId,
                started.pollInterval,
                (status) => {
                    const progressValue = typeof status.progress === 'number'
                        ? Math.min(100, Math.max(0, status.progress))
                        : 0;
                    setCategoryOperation(category, { progress: progressValue });
                }
            );

            if (finished.error || !finished.result) {
                onStatusUpdate(`[ERROR] ${CATEGORY_LABELS[category]}: ${finished.error || 'Job failed.'}`);
                return;
            }

            const rawResult = finished.result as Record<string, unknown>;
            const operationResult: NISTCategoryOperationResponse = {
                ...rawResult,
                status: typeof rawResult.status === 'string' ? rawResult.status : 'success',
                category,
            } as NISTCategoryOperationResponse;
            onSuccess(operationResult);
        } finally {
            finalizeCategoryOperation(category);
            await loadCategoryStatus();
        }
    }, [finalizeCategoryOperation, loadCategoryStatus, onStatusUpdate, operations, setCategoryOperation]);

    const handlePing = useCallback(async (category: NISTCategoryKey) => {
        if (operations[category].running) {
            return;
        }
        const result = await pingNistCategoryServer(category);
        if (result.error || !result.data) {
            onStatusUpdate(`[ERROR] ${CATEGORY_LABELS[category]}: ${result.error || 'Ping failed.'}`);
            return;
        }
        const pingData = result.data;

        setStatuses((previous) => ({
            ...previous,
            [category]: {
                ...previous[category],
                server_ok: pingData.server_ok,
                server_checked_at: pingData.checked_at,
            },
        }));
        const statusText = pingData.server_ok ? 'reachable' : 'unreachable';
        onStatusUpdate(`[INFO] ${CATEGORY_LABELS[category]} server is ${statusText}.`);
    }, [onStatusUpdate, operations]);

    const handleUpdateIndex = useCallback((category: NISTCategoryKey) => {
        void runCategoryJob(
            category,
            'index',
            () => startNistCategoryIndexJob(category),
            (result) => {
                onStatusUpdate(
                    [
                        `[INFO] ${CATEGORY_LABELS[category]} index updated.`,
                        '',
                        `- Available records: ${result.available_count ?? 0}`,
                    ].join('\n')
                );
            }
        );
    }, [onStatusUpdate, runCategoryJob]);

    const handleFetchRecords = useCallback((category: NISTCategoryKey) => {
        const fraction = normalizeFraction(fractions[category], 1.0);
        persistFraction(category, fraction);
        setFractions((previous) => ({ ...previous, [category]: fraction }));
        setFractionInputs((previous) => ({ ...previous, [category]: fraction.toFixed(3) }));

        void runCategoryJob(
            category,
            'fetch',
            () => startNistCategoryFetchJob(category, { fraction }),
            (result) => {
                onStatusUpdate(
                    [
                        `[INFO] ${CATEGORY_LABELS[category]} records updated.`,
                        '',
                        `- Requested records: ${result.requested_count ?? 0}`,
                        `- New records fetched: ${result.fetched_count ?? 0}`,
                        `- Local records: ${result.local_count ?? 0}`,
                    ].join('\n')
                );
            }
        );
    }, [fractions, onStatusUpdate, runCategoryJob]);

    const handleEnrich = useCallback((category: NISTCategoryKey) => {
        if (category === 'experiments') {
            return;
        }
        void runCategoryJob(
            category,
            'enrich',
            () => startNistCategoryEnrichJob(category),
            (result) => {
                onStatusUpdate(
                    [
                        `[INFO] ${CATEGORY_LABELS[category]} enrichment completed.`,
                        '',
                        `- Names requested: ${result.names_requested ?? 0}`,
                        `- Names matched: ${result.names_matched ?? 0}`,
                        `- Rows updated: ${result.rows_updated ?? 0}`,
                    ].join('\n')
                );
            }
        );
    }, [onStatusUpdate, runCategoryJob]);

    const rows = useMemo(() => CATEGORY_ORDER.map((category) => {
        const status = statuses[category];
        const operation = operations[category];
        const hasLocalData = status.local_count >= 1;
        const serverStateClass = status.server_ok === true
            ? 'is-online'
            : status.server_ok === false
                ? 'is-offline'
                : 'is-unknown';
        return (
            <div key={category} className="nist-category-row">
                <div className="nist-category-row-main">
                    <span
                        className={`nist-row-led-dot ${hasLocalData ? 'available' : 'empty'}`}
                        aria-hidden="true"
                    />
                    <span className="nist-row-name">{CATEGORY_LABELS[category]}</span>
                    <span className="nist-row-count">
                        {status.local_count} / {status.available_count}
                    </span>
                    <span className="nist-row-updated">{formatCompactDateTime(status.last_update)}</span>
                    <div className="nist-row-fraction-wrap">
                        <label htmlFor={`fraction-${category}`}>Fraction</label>
                        <input
                            id={`fraction-${category}`}
                            type="number"
                            min={FRACTION_MIN}
                            max={FRACTION_MAX}
                            step={FRACTION_STEP}
                            value={fractionInputs[category]}
                            onChange={(event) => handleFractionInput(category, event.target.value)}
                            onBlur={() => commitFraction(category)}
                            onKeyDown={(event) => {
                                if (event.key === 'Enter') {
                                    commitFraction(category);
                                }
                            }}
                            disabled={operation.running}
                        />
                    </div>
                </div>

                <div className="nist-category-row-actions">
                    <button
                        className={`nist-icon-button ${serverStateClass}`}
                        title="Server Status"
                        aria-label={`Server status for ${CATEGORY_LABELS[category]}`}
                        onClick={() => void handlePing(category)}
                        disabled={operation.running}
                    >
                        <PingIcon />
                    </button>
                    <button
                        className="nist-icon-button"
                        title="Update Index"
                        aria-label={`Update index for ${CATEGORY_LABELS[category]}`}
                        onClick={() => handleUpdateIndex(category)}
                        disabled={operation.running}
                    >
                        <IndexIcon />
                    </button>
                    <button
                        className="nist-icon-button"
                        title="Get Records"
                        aria-label={`Get records for ${CATEGORY_LABELS[category]}`}
                        onClick={() => handleFetchRecords(category)}
                        disabled={operation.running}
                    >
                        <DownloadIcon />
                    </button>
                    {status.supports_enrichment && (
                        <button
                            className="nist-icon-button"
                            title="Enrich Molecular Properties"
                            aria-label={`Enrich properties for ${CATEGORY_LABELS[category]}`}
                            onClick={() => handleEnrich(category)}
                            disabled={operation.running}
                        >
                            <EnrichIcon />
                        </button>
                    )}
                </div>

                {operation.running && (
                    <div className="nist-row-progress">
                        <span className="nist-spinner" aria-hidden="true" />
                        <span>{OPERATION_LABELS[operation.operation]} {operation.progress.toFixed(0)}%</span>
                        <div className="nist-row-progress-track" aria-hidden="true">
                            <div
                                className="nist-row-progress-fill"
                                style={{ width: `${operation.progress}%` }}
                            />
                        </div>
                    </div>
                )}
            </div>
        );
    }), [
        commitFraction,
        fractionInputs,
        handleEnrich,
        handleFetchRecords,
        handleFractionInput,
        handlePing,
        handleUpdateIndex,
        operations,
        statuses,
    ]);

    return (
        <div className="nist-rows-wrapper">
            {rows}
        </div>
    );
};

// app/client/src/app/features/nist/nist-collection-rows.component.ts
import { Component, EventEmitter, OnInit, Output, signal } from '@angular/core';
import {
    fetchNistCategoryStatus,
    pingNistCategoryServer,
    pollNistJobUntilComplete,
    startNistCategoryEnrichJob,
    startNistCategoryFetchJob,
    startNistCategoryIndexJob,
} from '../../services/nist.service';
import type { JobStartResult } from '../../services/job.service';
import type {
    NISTCategoryFetchRequest,
    NISTCategoryKey,
    NISTCategoryOperationResponse,
    NISTCategoryRecordStatus,
} from '../../models/nist.model';

type CategoryOperation = 'idle' | 'index' | 'fetch' | 'enrich';

interface CategoryOperationState {
    running: boolean;
    operation: CategoryOperation;
    progress: number;
}

interface NistActionIcon {
    viewBox: string;
    paths: string[];
}

const CATEGORY_ORDER: NISTCategoryKey[] = ['experiments', 'guest', 'host'];
const CATEGORY_LABELS: Record<NISTCategoryKey, string> = {
    experiments: 'Adsorption experiments',
    guest: 'Adsorbate species',
    host: 'Adsorbent materials',
};
const OPERATION_LABELS: Record<CategoryOperation, string> = {
    idle: 'Idle',
    index: 'Updating index',
    fetch: 'Fetching records',
    enrich: 'Enriching properties',
};
const ACTION_ICONS: Record<'server' | 'index' | 'fetch' | 'enrich', NistActionIcon> = {
    server: {
        viewBox: '0 0 24 24',
        paths: [
            'M2.25 8.25A2.25 2.25 0 0 1 4.5 6h15a2.25 2.25 0 0 1 2.25 2.25v2.25A2.25 2.25 0 0 1 19.5 12.75h-15A2.25 2.25 0 0 1 2.25 10.5V8.25Z',
            'M2.25 15.75A2.25 2.25 0 0 1 4.5 13.5h15a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 19.5 20.25h-15A2.25 2.25 0 0 1 2.25 18v-2.25Z',
            'M6.75 9.375h.008v.008H6.75v-.008Zm0 7.5h.008v.008H6.75v-.008Zm3-7.5h7.5m-7.5 7.5h7.5',
        ],
    },
    index: {
        viewBox: '0 0 24 24',
        paths: [
            'M4.5 5.25h15A1.5 1.5 0 0 1 21 6.75v10.5a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 17.25V6.75a1.5 1.5 0 0 1 1.5-1.5Z',
            'M7.5 9h9M7.5 12h9M7.5 15h5.25',
        ],
    },
    fetch: {
        viewBox: '0 0 24 24',
        paths: [
            'M12 3.75v10.5',
            'm8.25 10.5-6.75 6.75-6.75-6.75',
            'M4.5 16.5v1.125A2.625 2.625 0 0 0 7.125 20.25h9.75A2.625 2.625 0 0 0 19.5 17.625V16.5',
        ],
    },
    enrich: {
        viewBox: '0 0 24 24',
        paths: [
            'M12 3.75c.947 2.08 2.597 3.73 4.677 4.677C14.597 9.374 12.947 11.024 12 13.104c-.947-2.08-2.597-3.73-4.677-4.677C9.403 7.48 11.053 5.83 12 3.75Z',
            'M18 13.5c.552 1.213 1.537 2.198 2.75 2.75-1.213.552-2.198 1.537-2.75 2.75-.552-1.213-1.537-2.198-2.75-2.75 1.213-.552 2.198-1.537 2.75-2.75Z',
            'M6 14.25c.745 1.636 2.114 3.005 3.75 3.75C8.114 18.745 6.745 20.114 6 21.75c-.745-1.636-2.114-3.005-3.75-3.75 1.636-.745 3.005-2.114 3.75-3.75Z',
        ],
    },
};
const FRACTION_MIN = 0.001;
const FRACTION_MAX = 1.0;
const FRACTION_STEP = 0.001;

const fractionStorageKey = (category: NISTCategoryKey): string => `adsmod.nist.fraction.${category}`;
const clampFraction = (value: number): number => Math.min(FRACTION_MAX, Math.max(FRACTION_MIN, value));
const normalizeFraction = (value: unknown, fallback = 1.0): number => {
    if (typeof value !== 'number' || Number.isNaN(value)) {
        return fallback;
    }
    return clampFraction(Number(value.toFixed(3)));
};
const readPersistedFraction = (category: NISTCategoryKey): number => {
    if (typeof window === 'undefined') {
        return 1.0;
    }
    const rawValue = window.localStorage.getItem(fractionStorageKey(category));
    if (!rawValue) {
        return 1.0;
    }
    return normalizeFraction(Number.parseFloat(rawValue), 1.0);
};
const persistFraction = (category: NISTCategoryKey, value: number): void => {
    if (typeof window !== 'undefined') {
        window.localStorage.setItem(fractionStorageKey(category), value.toFixed(3));
    }
};
const formatCompactDateTime = (value: string | null): string => {
    if (!value) {
        return 'N.A.';
    }
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
        return 'N.A.';
    }
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    const hh = String(date.getHours()).padStart(2, '0');
    const min = String(date.getMinutes()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd} ${hh}:${min}`;
};
const emptyStatus = (category: NISTCategoryKey): NISTCategoryRecordStatus => ({
    category,
    local_count: 0,
    available_count: 0,
    last_update: null,
    server_ok: null,
    server_checked_at: null,
    supports_enrichment: category !== 'experiments',
});
const initialStatusMap = (): Record<NISTCategoryKey, NISTCategoryRecordStatus> => ({
    experiments: emptyStatus('experiments'),
    guest: emptyStatus('guest'),
    host: emptyStatus('host'),
});
const initialOperationMap = (): Record<NISTCategoryKey, CategoryOperationState> => ({
    experiments: { running: false, operation: 'idle', progress: 0 },
    guest: { running: false, operation: 'idle', progress: 0 },
    host: { running: false, operation: 'idle', progress: 0 },
});

@Component({
    selector: 'adsmod-nist-collection-rows',
    standalone: true,
    template: `
        <div class="reference-nist-table">
            <div class="reference-nist-header" role="row">
                <span>Status</span>
                <span>Category</span>
                <span>Count</span>
                <span>Last Updated</span>
                <span>Fraction</span>
                <span>Ping</span>
                <span>Index</span>
                <span>Fetch</span>
                <span>Enrich</span>
            </div>
            @for (category of categories; track category) {
                @let status = statuses()[category];
                @let operation = operations()[category];
                <div class="reference-nist-row" role="row">
                    <span
                        class="reference-status-dot"
                        [class.empty]="status.local_count < 1"
                        [class.slow]="status.server_ok === false"
                        aria-hidden="true"
                    ></span>
                    <span>{{ labels[category] }}</span>
                    <span><em>{{ formatCount(status) }}</em></span>
                    <span>{{ formatDate(status.last_update) }}</span>
                    <input
                        type="text"
                        [id]="'fraction-' + category"
                        [value]="fractionInputs()[category]"
                        [attr.aria-label]="'Fraction for ' + labels[category]"
                        [disabled]="operation.running"
                        (input)="handleFractionInput(category, $event)"
                        (blur)="commitFraction(category)"
                        (keydown.enter)="commitFraction(category)"
                    />
                    <button
                        class="nist-icon-button"
                        type="button"
                        [disabled]="operation.running"
                        [attr.aria-label]="'Ping ' + labels[category]"
                        (click)="handlePing(category)"
                    >
                        <svg aria-hidden="true" [attr.viewBox]="actionIcons.server.viewBox" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                            @for (path of actionIcons.server.paths; track path) {
                                <path [attr.d]="path"></path>
                            }
                        </svg>
                    </button>
                    <button
                        class="nist-icon-button"
                        type="button"
                        [disabled]="operation.running"
                        [attr.aria-label]="'Index ' + labels[category]"
                        (click)="handleUpdateIndex(category)"
                    >
                        <svg aria-hidden="true" [attr.viewBox]="actionIcons.index.viewBox" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                            @for (path of actionIcons.index.paths; track path) {
                                <path [attr.d]="path"></path>
                            }
                        </svg>
                    </button>
                    <button
                        class="nist-icon-button"
                        type="button"
                        [disabled]="operation.running"
                        [attr.aria-label]="'Fetch ' + labels[category]"
                        (click)="handleFetchRecords(category)"
                    >
                        <svg aria-hidden="true" [attr.viewBox]="actionIcons.fetch.viewBox" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                            @for (path of actionIcons.fetch.paths; track path) {
                                <path [attr.d]="path"></path>
                            }
                        </svg>
                    </button>
                    <button
                        class="nist-icon-button"
                        type="button"
                        [disabled]="operation.running || !status.supports_enrichment"
                        [attr.aria-label]="'Enrich ' + labels[category]"
                        (click)="handleEnrich(category)"
                    >
                        <svg aria-hidden="true" [attr.viewBox]="actionIcons.enrich.viewBox" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                            @for (path of actionIcons.enrich.paths; track path) {
                                <path [attr.d]="path"></path>
                            }
                        </svg>
                    </button>
                </div>
                @if (operation.running) {
                    <div class="reference-nist-progress" role="status">
                        <span>{{ operationLabels[operation.operation] }}</span>
                        <progress max="100" [value]="operation.progress"></progress>
                        <span>{{ operation.progress }}%</span>
                    </div>
                }
            }
            <div class="reference-nist-footer">
                <span>Total Categories: <strong>{{ categories.length }}</strong></span>
                <span>Total Records: <strong>{{ totalLocalRecords() }}</strong></span>
                <span>↻ Last refreshed: {{ lastRefreshedLabel() }}</span>
            </div>
        </div>
    `,
})
export class NistCollectionRowsComponent implements OnInit {
    @Output() readonly statusUpdate = new EventEmitter<string>();

    protected readonly categories = CATEGORY_ORDER;
    protected readonly labels = CATEGORY_LABELS;
    protected readonly operationLabels = OPERATION_LABELS;
    protected readonly fractionMin = FRACTION_MIN;
    protected readonly fractionMax = FRACTION_MAX;
    protected readonly fractionStep = FRACTION_STEP;
    protected readonly actionIcons = ACTION_ICONS;
    protected readonly statuses = signal<Record<NISTCategoryKey, NISTCategoryRecordStatus>>(initialStatusMap());
    protected readonly operations = signal<Record<NISTCategoryKey, CategoryOperationState>>(initialOperationMap());
    protected readonly fractions = signal<Record<NISTCategoryKey, number>>({
        experiments: readPersistedFraction('experiments'),
        guest: readPersistedFraction('guest'),
        host: readPersistedFraction('host'),
    });
    protected readonly fractionInputs = signal<Record<NISTCategoryKey, string>>({
        experiments: readPersistedFraction('experiments').toFixed(3),
        guest: readPersistedFraction('guest').toFixed(3),
        host: readPersistedFraction('host').toFixed(3),
    });

    ngOnInit(): void {
        void this.loadCategoryStatus();
    }

    protected formatDate(value: string | null): string {
        return formatCompactDateTime(value);
    }

    protected serverStateClass(status: NISTCategoryRecordStatus): string {
        if (status.server_ok === true) {
            return 'is-online';
        }
        if (status.server_ok === false) {
            return 'is-offline';
        }
        return 'is-unknown';
    }

    protected formatCount(status: NISTCategoryRecordStatus): string {
        if (status.available_count > 0) {
            return `${status.local_count.toLocaleString()} / ${status.available_count.toLocaleString()}`;
        }
        return status.local_count.toLocaleString();
    }

    protected totalLocalRecords(): string {
        return this.categories
            .reduce((total, category) => total + this.statuses()[category].local_count, 0)
            .toLocaleString();
    }

    protected lastRefreshedLabel(): string {
        const latestTimestamp = this.categories
            .map((category) => this.statuses()[category].last_update)
            .filter((value): value is string => Boolean(value))
            .map((value) => new Date(value).getTime())
            .filter((value) => !Number.isNaN(value))
            .sort((left, right) => right - left)[0];
        return typeof latestTimestamp === 'number' ? formatCompactDateTime(new Date(latestTimestamp).toISOString()) : 'N.A.';
    }

    protected handleFractionInput(category: NISTCategoryKey, event: Event): void {
        const input = event.target as HTMLInputElement;
        this.fractionInputs.update((previous) => ({ ...previous, [category]: input.value }));
        const parsed = Number.parseFloat(input.value);
        if (Number.isFinite(parsed)) {
            this.fractions.update((previous) => ({ ...previous, [category]: normalizeFraction(parsed, 1.0) }));
        }
    }

    protected commitFraction(category: NISTCategoryKey): void {
        const parsed = Number.parseFloat(this.fractionInputs()[category]);
        const normalized = Number.isFinite(parsed)
            ? normalizeFraction(parsed, this.fractions()[category])
            : normalizeFraction(this.fractions()[category], 1.0);
        persistFraction(category, normalized);
        this.fractions.update((previous) => ({ ...previous, [category]: normalized }));
        this.fractionInputs.update((previous) => ({ ...previous, [category]: normalized.toFixed(3) }));
    }

    protected async handlePing(category: NISTCategoryKey): Promise<void> {
        if (this.operations()[category].running) {
            return;
        }
        const result = await pingNistCategoryServer(category);
        if (result.error || !result.data) {
            this.statusUpdate.emit(`[ERROR] ${CATEGORY_LABELS[category]}: ${result.error || 'Ping failed.'}`);
            return;
        }
        const pingData = result.data;
        this.statuses.update((previous) => ({
            ...previous,
            [category]: {
                ...previous[category],
                server_ok: pingData.server_ok,
                server_checked_at: pingData.checked_at,
            },
        }));
        this.statusUpdate.emit(`[INFO] ${CATEGORY_LABELS[category]} server is ${pingData.server_ok ? 'reachable' : 'unreachable'}.`);
    }

    protected handleUpdateIndex(category: NISTCategoryKey): void {
        void this.runCategoryJob(category, 'index', () => startNistCategoryIndexJob(category), (result) => {
            this.statusUpdate.emit([
                `[INFO] ${CATEGORY_LABELS[category]} index updated.`,
                '',
                `- Available records: ${result.available_count ?? 0}`,
            ].join('\n'));
        });
    }

    protected handleFetchRecords(category: NISTCategoryKey): void {
        const fraction = normalizeFraction(this.fractions()[category], 1.0);
        persistFraction(category, fraction);
        this.fractions.update((previous) => ({ ...previous, [category]: fraction }));
        this.fractionInputs.update((previous) => ({ ...previous, [category]: fraction.toFixed(3) }));
        const payload: NISTCategoryFetchRequest = { fraction };
        void this.runCategoryJob(category, 'fetch', () => startNistCategoryFetchJob(category, payload), (result) => {
            this.statusUpdate.emit([
                `[INFO] ${CATEGORY_LABELS[category]} records updated.`,
                '',
                `- Requested records: ${result.requested_count ?? 0}`,
                `- New records fetched: ${result.fetched_count ?? 0}`,
                `- Local records: ${result.local_count ?? 0}`,
            ].join('\n'));
        });
    }

    protected handleEnrich(category: NISTCategoryKey): void {
        if (category === 'experiments') {
            return;
        }
        void this.runCategoryJob(category, 'enrich', () => startNistCategoryEnrichJob(category), (result) => {
            this.statusUpdate.emit([
                `[INFO] ${CATEGORY_LABELS[category]} enrichment completed.`,
                '',
                `- Names requested: ${result.names_requested ?? 0}`,
                `- Names matched: ${result.names_matched ?? 0}`,
                `- Rows updated: ${result.rows_updated ?? 0}`,
            ].join('\n'));
        });
    }

    private async loadCategoryStatus(): Promise<void> {
        const result = await fetchNistCategoryStatus();
        if (result.error || !result.data) {
            return;
        }
        const updatedStatus = initialStatusMap();
        result.data.categories.forEach((item) => {
            updatedStatus[item.category] = item;
        });
        this.statuses.set(updatedStatus);
    }

    private async runCategoryJob(
        category: NISTCategoryKey,
        operation: CategoryOperation,
        startJob: () => Promise<JobStartResult>,
        onSuccess: (result: NISTCategoryOperationResponse) => void
    ): Promise<void> {
        if (this.operations()[category].running) {
            return;
        }
        this.setCategoryOperation(category, { running: true, operation, progress: 0 });
        try {
            const started = await startJob();
            if (started.error || !started.jobId) {
                this.statusUpdate.emit(`[ERROR] ${CATEGORY_LABELS[category]}: ${started.error || 'Unable to start job.'}`);
                return;
            }
            const finished = await pollNistJobUntilComplete(started.jobId, started.pollInterval, (status) => {
                const progressValue = typeof status.progress === 'number' ? Math.min(100, Math.max(0, status.progress)) : 0;
                this.setCategoryOperation(category, { progress: progressValue });
            });
            if (finished.error || !finished.result) {
                this.statusUpdate.emit(`[ERROR] ${CATEGORY_LABELS[category]}: ${finished.error || 'Job failed.'}`);
                return;
            }
            const rawResult = finished.result;
            onSuccess({
                ...rawResult,
                status: typeof rawResult['status'] === 'string' ? rawResult['status'] : 'success',
                category,
            } as NISTCategoryOperationResponse);
        } finally {
            this.setCategoryOperation(category, { running: false, operation: 'idle', progress: 0 });
            await this.loadCategoryStatus();
        }
    }

    private setCategoryOperation(category: NISTCategoryKey, update: Partial<CategoryOperationState>): void {
        this.operations.update((previous) => ({
            ...previous,
            [category]: { ...previous[category], ...update },
        }));
    }
}
