// ADSMOD/client/src/components/ResumeTrainingWizard.tsx

import React, { useEffect } from 'react';
import { NumberInput } from './UIComponents';
import { WizardProgressIndicator } from './WizardProgressIndicator';
import { useWizardPagination } from '../hooks/useWizardPagination';
import type { CheckpointInfo, ResumeTrainingConfig } from '../types';

interface ResumeTrainingWizardProps {
    checkpoints: CheckpointInfo[];
    config: ResumeTrainingConfig;
    onConfigChange: (config: ResumeTrainingConfig) => void;
    onClose: () => void;
    onConfirm: () => void;
    isLoading: boolean;
    selectedCheckpointName: string; // Now required and pre-selected
}

export const ResumeTrainingWizard: React.FC<ResumeTrainingWizardProps> = ({
    checkpoints,
    config,
    onConfigChange,
    onClose,
    onConfirm,
    isLoading,
    selectedCheckpointName,
}) => {
    const {
        currentPage,
        isFirstPage,
        isLastPage,
        goToNextPage,
        goToPreviousPage,
    } = useWizardPagination(1);
    const dialogTitleId = 'resume-training-wizard-title';

    // Ensure the checkpoint name is set in the config on mount
    useEffect(() => {
        if (config.checkpoint_name !== selectedCheckpointName) {
            onConfigChange({ ...config, checkpoint_name: selectedCheckpointName });
        }
    }, [selectedCheckpointName, config, onConfigChange]);

    const updateConfig = <K extends keyof ResumeTrainingConfig>(key: K, value: ResumeTrainingConfig[K]) => {
        onConfigChange({ ...config, [key]: value });
    };

    const selectedCheckpoint = checkpoints.find((checkpoint) => checkpoint.name === selectedCheckpointName) || null;
    const compatibilityLabel = selectedCheckpoint
        ? selectedCheckpoint.is_compatible
            ? 'Compatible'
            : 'Incompatible'
        : 'Unknown';

    return (
        <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby={dialogTitleId}>
            <div className="wizard-modal">
                <div className="wizard-header">
                    <h4 id={dialogTitleId}>Resume Training Wizard</h4>
                    <p>Resuming from checkpoint: <strong>{selectedCheckpointName}</strong></p>
                    <WizardProgressIndicator currentPage={currentPage} totalPages={2} />
                </div>

                <div className="wizard-body">
                    {currentPage === 0 && (
                        <div className="wizard-page">
                            <div className="wizard-card">
                                <div className="wizard-card-header">
                                    <span className="wizard-card-icon">CP</span>
                                    <span>Configuration</span>
                                </div>
                                <p className="wizard-card-description">
                                    Set the number of additional epochs to train.
                                </p>
                                <div className="wizard-card-body">
                                    <div className="wizard-settings-grid">
                                        <NumberInput
                                            label="Additional Epochs"
                                            value={config.additional_epochs}
                                            onChange={(value) => updateConfig('additional_epochs', value)}
                                            min={1}
                                            max={100}
                                            step={1}
                                            precision={0}
                                        />
                                    </div>
                                    <div style={{ marginTop: '20px', padding: '15px', backgroundColor: 'var(--slate-50)', borderRadius: '8px' }}>
                                        <strong>Checkpoint Details:</strong>
                                        <ul style={{ listStyle: 'none', padding: 0, marginTop: '10px' }}>
                                            <li>Compatibility: {compatibilityLabel}</li>
                                            <li>Epochs Trained: {selectedCheckpoint?.epochs_trained ?? '--'}</li>
                                            <li>Final Loss: {selectedCheckpoint?.final_loss?.toFixed(4) ?? '--'}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {currentPage === 1 && (
                        <div className="wizard-page">
                            <div className="wizard-summary">
                                <div className="wizard-summary-section">
                                    <h5>Resume Configuration</h5>
                                    <div className="wizard-summary-grid">
                                        <span>Checkpoint</span>
                                        <strong>{selectedCheckpointName}</strong>
                                        <span>Additional epochs</span>
                                        <strong>{config.additional_epochs}</strong>
                                        <span>Compatibility</span>
                                        <strong>{compatibilityLabel}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                <div className="wizard-footer">
                    <button className="secondary" onClick={onClose} disabled={isLoading}>
                        Cancel
                    </button>
                    {!isFirstPage && (
                        <button className="secondary" onClick={goToPreviousPage} disabled={isLoading}>
                            Previous
                        </button>
                    )}
                    {!isLastPage && (
                        <button className="primary" onClick={goToNextPage} disabled={isLoading}>
                            Next
                        </button>
                    )}
                    {isLastPage && (
                        <button className="primary" onClick={onConfirm} disabled={isLoading}>
                            {isLoading ? 'Resuming...' : 'Confirm Resume'}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default ResumeTrainingWizard;

// app/client/src/app/features/training/components/resume-training-wizard.component.ts
import { Component, computed, input, output, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import type { CheckpointInfo, ResumeTrainingConfig } from '../../../models/training.model';
import { NumberInputComponent } from '../../../shared/components/number-input/number-input.component';
import { WizardNavigationFooterComponent } from './wizard-navigation-footer.component';
import { WizardProgressIndicatorComponent } from './wizard-progress-indicator.component';

@Component({
    selector: 'adsmod-resume-training-wizard',
    standalone: true,
    imports: [ReactiveFormsModule, NumberInputComponent, WizardNavigationFooterComponent, WizardProgressIndicatorComponent],
    template: `
        <div class="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="resume-training-wizard-title">
            <div class="wizard-modal">
                <div class="wizard-header">
                    <h4 id="resume-training-wizard-title">Resume Training Wizard</h4>
                    <p>Resuming from checkpoint: <strong>{{ selectedCheckpointName() }}</strong></p>
                    <adsmod-wizard-progress-indicator [currentPage]="currentPage()" [totalPages]="2" />
                </div>

                <div class="wizard-body">
                    @if (currentPage() === 0) {
                        <div class="wizard-page">
                            <div class="wizard-card">
                                <div class="wizard-card-header"><span class="wizard-card-icon">CP</span><span>Configuration</span></div>
                                <p class="wizard-card-description">Set the number of additional epochs to train.</p>
                                <div class="wizard-card-body">
                                    <div class="wizard-settings-grid">
                                        <adsmod-number-input label="Additional Epochs" [value]="additionalEpochs()" [min]="1" [max]="100" [step]="1" [precision]="0" (valueChange)="additionalEpochsControl.setValue($event)" />
                                    </div>
                                    <div style="margin-top: 20px; padding: 15px; background-color: var(--slate-50); border-radius: 8px;">
                                        <strong>Checkpoint Details:</strong>
                                        <ul style="list-style: none; padding: 0; margin-top: 10px;">
                                            <li>Compatibility: {{ compatibilityLabel() }}</li>
                                            <li>Epochs Trained: {{ selectedCheckpoint()?.epochs_trained ?? '--' }}</li>
                                            <li>Final Loss: {{ selectedCheckpoint()?.final_loss?.toFixed(4) ?? '--' }}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    } @else {
                        <div class="wizard-page">
                            <div class="wizard-summary">
                                <div class="wizard-summary-section">
                                    <h5>Resume Configuration</h5>
                                    <div class="wizard-summary-grid">
                                        <span>Checkpoint</span><strong>{{ selectedCheckpointName() }}</strong>
                                        <span>Additional epochs</span><strong>{{ additionalEpochs() }}</strong>
                                        <span>Compatibility</span><strong>{{ compatibilityLabel() }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>

                <adsmod-wizard-navigation-footer
                    [isLoading]="isLoading()"
                    [isFirstPage]="currentPage() === 0"
                    [isLastPage]="currentPage() === 1"
                    confirmIdleLabel="Confirm Resume"
                    confirmLoadingLabel="Resuming..."
                    (closed)="closed.emit()"
                    (next)="currentPage.set(1)"
                    (previous)="currentPage.set(0)"
                    (confirmed)="confirm()"
                />
            </div>
        </div>
    `,
})
export class ResumeTrainingWizardComponent {
    readonly checkpoints = input.required<CheckpointInfo[]>();
    readonly selectedCheckpointName = input.required<string>();
    readonly initialConfig = input.required<ResumeTrainingConfig>();
    readonly isLoading = input(false);
    readonly closed = output<void>();
    readonly confirmed = output<ResumeTrainingConfig>();
    protected readonly currentPage = signal(0);
    protected readonly additionalEpochsControl = new FormControl(10, { nonNullable: true, validators: [Validators.min(1)] });
    protected readonly additionalEpochs = computed(() => this.additionalEpochsControl.value);
    protected readonly selectedCheckpoint = computed(() => this.checkpoints().find((checkpoint) => checkpoint.name === this.selectedCheckpointName()) ?? null);
    protected readonly compatibilityLabel = computed(() => this.selectedCheckpoint()?.is_compatible ? 'Compatible' : this.selectedCheckpoint() ? 'Incompatible' : 'Unknown');

    constructor() {
        queueMicrotask(() => this.additionalEpochsControl.setValue(this.initialConfig().additional_epochs));
    }

    protected confirm(): void {
        this.confirmed.emit({
            checkpoint_name: this.selectedCheckpointName(),
            additional_epochs: this.additionalEpochsControl.value,
        });
    }
}
