// ADSMOD/client/src/features/training/components/SplitSelectionCard.tsx
import React from 'react';

interface SplitSelectionCardProps {
    title: string;
    subtitle?: string;
    refreshLabel?: string;
    onRefresh?: () => void;
    leftContent: React.ReactNode;
    rightContent: React.ReactNode;
}

export const SplitSelectionCard: React.FC<SplitSelectionCardProps> = ({
    title,
    subtitle,
    refreshLabel = 'Refresh',
    onRefresh,
    leftContent,
    rightContent,
}) => {
    return (
        <div className="section-container">
            <h3 className="split-selection-title">{title}</h3>
            {subtitle && <p className="split-selection-subtitle">{subtitle}</p>}
            <div className="split-selection-card">
                <div className="split-selection-card-left">
                    <div className="split-selection-card-toolbar">
                        {onRefresh && (
                            <button
                                type="button"
                                className="split-selection-refresh-button"
                                onClick={(event) => {
                                    event.stopPropagation();
                                    onRefresh();
                                }}
                            >
                                🔄 {refreshLabel}
                            </button>
                        )}
                    </div>
                    <div className="split-selection-card-content">{leftContent}</div>
                </div>
                <div className="split-selection-card-right">{rightContent}</div>
            </div>
        </div>
    );
};

export default SplitSelectionCard;

// app/client/src/app/features/training/components/split-selection-card.component.ts
import { Component, input, output } from '@angular/core';

@Component({
    selector: 'adsmod-split-selection-card',
    standalone: true,
    template: `
        <div class="section-container">
            @if (!hideHeader()) {
                <h3 class="split-selection-title">{{ title() }}</h3>
            }
            @if (!hideHeader() && subtitle()) {
                <p class="split-selection-subtitle">{{ subtitle() }}</p>
            }
            <div class="split-selection-card">
                <div class="split-selection-card-left">
                    <div class="split-selection-card-toolbar">
                        @if (showRefresh()) {
                            <button
                                type="button"
                                class="split-selection-refresh-button"
                                (click)="refresh.emit()"
                            >
                                Refresh
                            </button>
                        }
                    </div>
                    <div class="split-selection-card-content">
                        <ng-content select="[card-left]"></ng-content>
                    </div>
                </div>
                <div class="split-selection-card-right">
                    <ng-content select="[card-right]"></ng-content>
                </div>
            </div>
        </div>
    `,
})
export class SplitSelectionCardComponent {
    readonly title = input.required<string>();
    readonly subtitle = input('');
    readonly hideHeader = input(false);
    readonly showRefresh = input(false);
    readonly refresh = output<void>();
}
