// ADSMOD/client/src/components/WizardProgressIndicator.tsx
import React from 'react';

interface WizardProgressIndicatorProps {
    currentPage: number;
    totalPages: number;
}

export const WizardProgressIndicator: React.FC<WizardProgressIndicatorProps> = ({
    currentPage,
    totalPages,
}) => {
    const pageNumbers = Array.from({ length: totalPages }, (_, index) => index + 1);

    return (
        <div className="wizard-page-indicator">
            {pageNumbers.map((pageNumber, index) => (
                <React.Fragment key={pageNumber}>
                    <span className={`wizard-dot ${currentPage === index ? 'active' : ''}`}>
                        {pageNumber}
                    </span>
                    {index < pageNumbers.length - 1 && (
                        <span className={`wizard-dot-line ${currentPage > index ? 'active' : ''}`} />
                    )}
                </React.Fragment>
            ))}
        </div>
    );
};

// app/client/src/app/features/training/components/wizard-progress-indicator.component.ts
// Copyright © 2023 Thomas Virdis
// Licensed under the MIT License.

import { Component, computed, input } from '@angular/core';

@Component({
    selector: 'adsmod-wizard-progress-indicator',
    standalone: true,
    template: `
        <div class="wizard-page-indicator">
            @for (page of pageNumbers(); track page; let index = $index) {
                <span class="wizard-dot" [class.active]="currentPage() === index">{{ page }}</span>
                @if (index < pageNumbers().length - 1) {
                    <span class="wizard-dot-line" [class.active]="currentPage() > index"></span>
                }
            }
        </div>
    `,
})
export class WizardProgressIndicatorComponent {
    readonly currentPage = input.required<number>();
    readonly totalPages = input.required<number>();
    protected readonly pageNumbers = computed(() => Array.from({ length: this.totalPages() }, (_, index) => index + 1));
}
