// app/ml_client/src/app/shared/components/metric-card/metric-card.component.ts
import { Component, input } from '@angular/core';

@Component({
    selector: 'adsmod-metric-card',
    standalone: true,
    template: `
        <div class="metric-card">
            <div class="metric-label">{{ label() }}</div>
            <div class="metric-value" [style.color]="color()">{{ value() }}</div>
        </div>
    `,
})
export class MetricCardComponent {
    readonly label = input.required<string>();
    readonly value = input.required<string>();
    readonly color = input('var(--primary-600)');
}

// app/ml_client/src/components/MetricCard.tsx
import React from 'react';

interface MetricCardProps {
    label: string;
    value: string;
    icon?: string;
    color?: string;
}

export const MetricCard: React.FC<MetricCardProps> = ({
    label,
    value,
    icon,
    color = 'var(--primary-600)',
}) => (
    <div className="metric-card">
        <div className="metric-label">{icon && <span className="metric-icon">{icon}</span>}{label}</div>
        <div className="metric-value" style={{ color }}>{value}</div>
    </div>
);
